/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as visitorInsightsVisitorsOverviewRouteImport } from './routes/(visitor-insights)/visitors-overview'
import { Route as visitorInsightsVisitorsRouteImport } from './routes/(visitor-insights)/visitors'
import { Route as visitorInsightsViewsRouteImport } from './routes/(visitor-insights)/views'
import { Route as visitorInsightsTopVisitorsRouteImport } from './routes/(visitor-insights)/top-visitors'
import { Route as visitorInsightsLoggedInUsersRouteImport } from './routes/(visitor-insights)/logged-in-users'

const PageAnalyticsLazyRouteImport = createFileRoute('/page-analytics')()
const OverviewLazyRouteImport = createFileRoute('/overview')()
const GeographicLazyRouteImport = createFileRoute('/geographic')()
const DevicesLazyRouteImport = createFileRoute('/devices')()
const CategoryAnalyticsLazyRouteImport = createFileRoute(
  '/category-analytics',
)()
const AuthorAnalyticsLazyRouteImport = createFileRoute('/author-analytics')()
const SettingsPrivacyLazyRouteImport = createFileRoute('/settings/privacy')()
const SettingsNotificationsLazyRouteImport = createFileRoute(
  '/settings/notifications',
)()
const SettingsGeneralLazyRouteImport = createFileRoute('/settings/general')()
const SettingsExclusionsLazyRouteImport = createFileRoute(
  '/settings/exclusions',
)()
const SettingsAdvancedLazyRouteImport = createFileRoute('/settings/advanced')()
const visitorInsightsSearchTermsLazyRouteImport = createFileRoute(
  '/(visitor-insights)/search-terms',
)()
const visitorInsightsOnlineVisitorsLazyRouteImport = createFileRoute(
  '/(visitor-insights)/online-visitors',
)()
const referralsSourceCategoriesLazyRouteImport = createFileRoute(
  '/(referrals)/source-categories',
)()
const referralsSocialMediaLazyRouteImport = createFileRoute(
  '/(referrals)/social-media',
)()
const referralsSearchEnginesLazyRouteImport = createFileRoute(
  '/(referrals)/search-engines',
)()
const referralsReferrersLazyRouteImport = createFileRoute(
  '/(referrals)/referrers',
)()
const referralsReferredVisitorsLazyRouteImport = createFileRoute(
  '/(referrals)/referred-visitors',
)()

const PageAnalyticsLazyRoute = PageAnalyticsLazyRouteImport.update({
  id: '/page-analytics',
  path: '/page-analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/page-analytics.lazy').then((d) => d.Route),
)
const OverviewLazyRoute = OverviewLazyRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/overview.lazy').then((d) => d.Route))
const GeographicLazyRoute = GeographicLazyRouteImport.update({
  id: '/geographic',
  path: '/geographic',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/geographic.lazy').then((d) => d.Route))
const DevicesLazyRoute = DevicesLazyRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/devices.lazy').then((d) => d.Route))
const CategoryAnalyticsLazyRoute = CategoryAnalyticsLazyRouteImport.update({
  id: '/category-analytics',
  path: '/category-analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/category-analytics.lazy').then((d) => d.Route),
)
const AuthorAnalyticsLazyRoute = AuthorAnalyticsLazyRouteImport.update({
  id: '/author-analytics',
  path: '/author-analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/author-analytics.lazy').then((d) => d.Route),
)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPrivacyLazyRoute = SettingsPrivacyLazyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/privacy.lazy').then((d) => d.Route),
)
const SettingsNotificationsLazyRoute =
  SettingsNotificationsLazyRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => SettingsRouteRoute,
  } as any).lazy(() =>
    import('./routes/settings/notifications.lazy').then((d) => d.Route),
  )
const SettingsGeneralLazyRoute = SettingsGeneralLazyRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/general.lazy').then((d) => d.Route),
)
const SettingsExclusionsLazyRoute = SettingsExclusionsLazyRouteImport.update({
  id: '/exclusions',
  path: '/exclusions',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/exclusions.lazy').then((d) => d.Route),
)
const SettingsAdvancedLazyRoute = SettingsAdvancedLazyRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/advanced.lazy').then((d) => d.Route),
)
const visitorInsightsSearchTermsLazyRoute =
  visitorInsightsSearchTermsLazyRouteImport
    .update({
      id: '/(visitor-insights)/search-terms',
      path: '/search-terms',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(visitor-insights)/search-terms.lazy').then(
        (d) => d.Route,
      ),
    )
const visitorInsightsOnlineVisitorsLazyRoute =
  visitorInsightsOnlineVisitorsLazyRouteImport
    .update({
      id: '/(visitor-insights)/online-visitors',
      path: '/online-visitors',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(visitor-insights)/online-visitors.lazy').then(
        (d) => d.Route,
      ),
    )
const referralsSourceCategoriesLazyRoute =
  referralsSourceCategoriesLazyRouteImport
    .update({
      id: '/(referrals)/source-categories',
      path: '/source-categories',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(referrals)/source-categories.lazy').then(
        (d) => d.Route,
      ),
    )
const referralsSocialMediaLazyRoute = referralsSocialMediaLazyRouteImport
  .update({
    id: '/(referrals)/social-media',
    path: '/social-media',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(referrals)/social-media.lazy').then((d) => d.Route),
  )
const referralsSearchEnginesLazyRoute = referralsSearchEnginesLazyRouteImport
  .update({
    id: '/(referrals)/search-engines',
    path: '/search-engines',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(referrals)/search-engines.lazy').then((d) => d.Route),
  )
const referralsReferrersLazyRoute = referralsReferrersLazyRouteImport
  .update({
    id: '/(referrals)/referrers',
    path: '/referrers',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(referrals)/referrers.lazy').then((d) => d.Route),
  )
const referralsReferredVisitorsLazyRoute =
  referralsReferredVisitorsLazyRouteImport
    .update({
      id: '/(referrals)/referred-visitors',
      path: '/referred-visitors',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(referrals)/referred-visitors.lazy').then(
        (d) => d.Route,
      ),
    )
const visitorInsightsVisitorsOverviewRoute =
  visitorInsightsVisitorsOverviewRouteImport
    .update({
      id: '/(visitor-insights)/visitors-overview',
      path: '/visitors-overview',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(visitor-insights)/visitors-overview.lazy').then(
        (d) => d.Route,
      ),
    )
const visitorInsightsVisitorsRoute = visitorInsightsVisitorsRouteImport
  .update({
    id: '/(visitor-insights)/visitors',
    path: '/visitors',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(visitor-insights)/visitors.lazy').then((d) => d.Route),
  )
const visitorInsightsViewsRoute = visitorInsightsViewsRouteImport
  .update({
    id: '/(visitor-insights)/views',
    path: '/views',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(visitor-insights)/views.lazy').then((d) => d.Route),
  )
const visitorInsightsTopVisitorsRoute = visitorInsightsTopVisitorsRouteImport
  .update({
    id: '/(visitor-insights)/top-visitors',
    path: '/top-visitors',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(visitor-insights)/top-visitors.lazy').then(
      (d) => d.Route,
    ),
  )
const visitorInsightsLoggedInUsersRoute =
  visitorInsightsLoggedInUsersRouteImport
    .update({
      id: '/(visitor-insights)/logged-in-users',
      path: '/logged-in-users',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(visitor-insights)/logged-in-users.lazy').then(
        (d) => d.Route,
      ),
    )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/author-analytics': typeof AuthorAnalyticsLazyRoute
  '/category-analytics': typeof CategoryAnalyticsLazyRoute
  '/devices': typeof DevicesLazyRoute
  '/geographic': typeof GeographicLazyRoute
  '/overview': typeof OverviewLazyRoute
  '/page-analytics': typeof PageAnalyticsLazyRoute
  '/logged-in-users': typeof visitorInsightsLoggedInUsersRoute
  '/top-visitors': typeof visitorInsightsTopVisitorsRoute
  '/views': typeof visitorInsightsViewsRoute
  '/visitors': typeof visitorInsightsVisitorsRoute
  '/visitors-overview': typeof visitorInsightsVisitorsOverviewRoute
  '/referred-visitors': typeof referralsReferredVisitorsLazyRoute
  '/referrers': typeof referralsReferrersLazyRoute
  '/search-engines': typeof referralsSearchEnginesLazyRoute
  '/social-media': typeof referralsSocialMediaLazyRoute
  '/source-categories': typeof referralsSourceCategoriesLazyRoute
  '/online-visitors': typeof visitorInsightsOnlineVisitorsLazyRoute
  '/search-terms': typeof visitorInsightsSearchTermsLazyRoute
  '/settings/advanced': typeof SettingsAdvancedLazyRoute
  '/settings/exclusions': typeof SettingsExclusionsLazyRoute
  '/settings/general': typeof SettingsGeneralLazyRoute
  '/settings/notifications': typeof SettingsNotificationsLazyRoute
  '/settings/privacy': typeof SettingsPrivacyLazyRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/author-analytics': typeof AuthorAnalyticsLazyRoute
  '/category-analytics': typeof CategoryAnalyticsLazyRoute
  '/devices': typeof DevicesLazyRoute
  '/geographic': typeof GeographicLazyRoute
  '/overview': typeof OverviewLazyRoute
  '/page-analytics': typeof PageAnalyticsLazyRoute
  '/logged-in-users': typeof visitorInsightsLoggedInUsersRoute
  '/top-visitors': typeof visitorInsightsTopVisitorsRoute
  '/views': typeof visitorInsightsViewsRoute
  '/visitors': typeof visitorInsightsVisitorsRoute
  '/visitors-overview': typeof visitorInsightsVisitorsOverviewRoute
  '/referred-visitors': typeof referralsReferredVisitorsLazyRoute
  '/referrers': typeof referralsReferrersLazyRoute
  '/search-engines': typeof referralsSearchEnginesLazyRoute
  '/social-media': typeof referralsSocialMediaLazyRoute
  '/source-categories': typeof referralsSourceCategoriesLazyRoute
  '/online-visitors': typeof visitorInsightsOnlineVisitorsLazyRoute
  '/search-terms': typeof visitorInsightsSearchTermsLazyRoute
  '/settings/advanced': typeof SettingsAdvancedLazyRoute
  '/settings/exclusions': typeof SettingsExclusionsLazyRoute
  '/settings/general': typeof SettingsGeneralLazyRoute
  '/settings/notifications': typeof SettingsNotificationsLazyRoute
  '/settings/privacy': typeof SettingsPrivacyLazyRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/author-analytics': typeof AuthorAnalyticsLazyRoute
  '/category-analytics': typeof CategoryAnalyticsLazyRoute
  '/devices': typeof DevicesLazyRoute
  '/geographic': typeof GeographicLazyRoute
  '/overview': typeof OverviewLazyRoute
  '/page-analytics': typeof PageAnalyticsLazyRoute
  '/(visitor-insights)/logged-in-users': typeof visitorInsightsLoggedInUsersRoute
  '/(visitor-insights)/top-visitors': typeof visitorInsightsTopVisitorsRoute
  '/(visitor-insights)/views': typeof visitorInsightsViewsRoute
  '/(visitor-insights)/visitors': typeof visitorInsightsVisitorsRoute
  '/(visitor-insights)/visitors-overview': typeof visitorInsightsVisitorsOverviewRoute
  '/(referrals)/referred-visitors': typeof referralsReferredVisitorsLazyRoute
  '/(referrals)/referrers': typeof referralsReferrersLazyRoute
  '/(referrals)/search-engines': typeof referralsSearchEnginesLazyRoute
  '/(referrals)/social-media': typeof referralsSocialMediaLazyRoute
  '/(referrals)/source-categories': typeof referralsSourceCategoriesLazyRoute
  '/(visitor-insights)/online-visitors': typeof visitorInsightsOnlineVisitorsLazyRoute
  '/(visitor-insights)/search-terms': typeof visitorInsightsSearchTermsLazyRoute
  '/settings/advanced': typeof SettingsAdvancedLazyRoute
  '/settings/exclusions': typeof SettingsExclusionsLazyRoute
  '/settings/general': typeof SettingsGeneralLazyRoute
  '/settings/notifications': typeof SettingsNotificationsLazyRoute
  '/settings/privacy': typeof SettingsPrivacyLazyRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/author-analytics'
    | '/category-analytics'
    | '/devices'
    | '/geographic'
    | '/overview'
    | '/page-analytics'
    | '/logged-in-users'
    | '/top-visitors'
    | '/views'
    | '/visitors'
    | '/visitors-overview'
    | '/referred-visitors'
    | '/referrers'
    | '/search-engines'
    | '/social-media'
    | '/source-categories'
    | '/online-visitors'
    | '/search-terms'
    | '/settings/advanced'
    | '/settings/exclusions'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/author-analytics'
    | '/category-analytics'
    | '/devices'
    | '/geographic'
    | '/overview'
    | '/page-analytics'
    | '/logged-in-users'
    | '/top-visitors'
    | '/views'
    | '/visitors'
    | '/visitors-overview'
    | '/referred-visitors'
    | '/referrers'
    | '/search-engines'
    | '/social-media'
    | '/source-categories'
    | '/online-visitors'
    | '/search-terms'
    | '/settings/advanced'
    | '/settings/exclusions'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/author-analytics'
    | '/category-analytics'
    | '/devices'
    | '/geographic'
    | '/overview'
    | '/page-analytics'
    | '/(visitor-insights)/logged-in-users'
    | '/(visitor-insights)/top-visitors'
    | '/(visitor-insights)/views'
    | '/(visitor-insights)/visitors'
    | '/(visitor-insights)/visitors-overview'
    | '/(referrals)/referred-visitors'
    | '/(referrals)/referrers'
    | '/(referrals)/search-engines'
    | '/(referrals)/social-media'
    | '/(referrals)/source-categories'
    | '/(visitor-insights)/online-visitors'
    | '/(visitor-insights)/search-terms'
    | '/settings/advanced'
    | '/settings/exclusions'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AuthorAnalyticsLazyRoute: typeof AuthorAnalyticsLazyRoute
  CategoryAnalyticsLazyRoute: typeof CategoryAnalyticsLazyRoute
  DevicesLazyRoute: typeof DevicesLazyRoute
  GeographicLazyRoute: typeof GeographicLazyRoute
  OverviewLazyRoute: typeof OverviewLazyRoute
  PageAnalyticsLazyRoute: typeof PageAnalyticsLazyRoute
  visitorInsightsLoggedInUsersRoute: typeof visitorInsightsLoggedInUsersRoute
  visitorInsightsTopVisitorsRoute: typeof visitorInsightsTopVisitorsRoute
  visitorInsightsViewsRoute: typeof visitorInsightsViewsRoute
  visitorInsightsVisitorsRoute: typeof visitorInsightsVisitorsRoute
  visitorInsightsVisitorsOverviewRoute: typeof visitorInsightsVisitorsOverviewRoute
  referralsReferredVisitorsLazyRoute: typeof referralsReferredVisitorsLazyRoute
  referralsReferrersLazyRoute: typeof referralsReferrersLazyRoute
  referralsSearchEnginesLazyRoute: typeof referralsSearchEnginesLazyRoute
  referralsSocialMediaLazyRoute: typeof referralsSocialMediaLazyRoute
  referralsSourceCategoriesLazyRoute: typeof referralsSourceCategoriesLazyRoute
  visitorInsightsOnlineVisitorsLazyRoute: typeof visitorInsightsOnlineVisitorsLazyRoute
  visitorInsightsSearchTermsLazyRoute: typeof visitorInsightsSearchTermsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/page-analytics': {
      id: '/page-analytics'
      path: '/page-analytics'
      fullPath: '/page-analytics'
      preLoaderRoute: typeof PageAnalyticsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geographic': {
      id: '/geographic'
      path: '/geographic'
      fullPath: '/geographic'
      preLoaderRoute: typeof GeographicLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category-analytics': {
      id: '/category-analytics'
      path: '/category-analytics'
      fullPath: '/category-analytics'
      preLoaderRoute: typeof CategoryAnalyticsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author-analytics': {
      id: '/author-analytics'
      path: '/author-analytics'
      fullPath: '/author-analytics'
      preLoaderRoute: typeof AuthorAnalyticsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/exclusions': {
      id: '/settings/exclusions'
      path: '/exclusions'
      fullPath: '/settings/exclusions'
      preLoaderRoute: typeof SettingsExclusionsLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/advanced': {
      id: '/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof SettingsAdvancedLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/(visitor-insights)/search-terms': {
      id: '/(visitor-insights)/search-terms'
      path: '/search-terms'
      fullPath: '/search-terms'
      preLoaderRoute: typeof visitorInsightsSearchTermsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visitor-insights)/online-visitors': {
      id: '/(visitor-insights)/online-visitors'
      path: '/online-visitors'
      fullPath: '/online-visitors'
      preLoaderRoute: typeof visitorInsightsOnlineVisitorsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(referrals)/source-categories': {
      id: '/(referrals)/source-categories'
      path: '/source-categories'
      fullPath: '/source-categories'
      preLoaderRoute: typeof referralsSourceCategoriesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(referrals)/social-media': {
      id: '/(referrals)/social-media'
      path: '/social-media'
      fullPath: '/social-media'
      preLoaderRoute: typeof referralsSocialMediaLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(referrals)/search-engines': {
      id: '/(referrals)/search-engines'
      path: '/search-engines'
      fullPath: '/search-engines'
      preLoaderRoute: typeof referralsSearchEnginesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(referrals)/referrers': {
      id: '/(referrals)/referrers'
      path: '/referrers'
      fullPath: '/referrers'
      preLoaderRoute: typeof referralsReferrersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(referrals)/referred-visitors': {
      id: '/(referrals)/referred-visitors'
      path: '/referred-visitors'
      fullPath: '/referred-visitors'
      preLoaderRoute: typeof referralsReferredVisitorsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visitor-insights)/visitors-overview': {
      id: '/(visitor-insights)/visitors-overview'
      path: '/visitors-overview'
      fullPath: '/visitors-overview'
      preLoaderRoute: typeof visitorInsightsVisitorsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visitor-insights)/visitors': {
      id: '/(visitor-insights)/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof visitorInsightsVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visitor-insights)/views': {
      id: '/(visitor-insights)/views'
      path: '/views'
      fullPath: '/views'
      preLoaderRoute: typeof visitorInsightsViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visitor-insights)/top-visitors': {
      id: '/(visitor-insights)/top-visitors'
      path: '/top-visitors'
      fullPath: '/top-visitors'
      preLoaderRoute: typeof visitorInsightsTopVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visitor-insights)/logged-in-users': {
      id: '/(visitor-insights)/logged-in-users'
      path: '/logged-in-users'
      fullPath: '/logged-in-users'
      preLoaderRoute: typeof visitorInsightsLoggedInUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsAdvancedLazyRoute: typeof SettingsAdvancedLazyRoute
  SettingsExclusionsLazyRoute: typeof SettingsExclusionsLazyRoute
  SettingsGeneralLazyRoute: typeof SettingsGeneralLazyRoute
  SettingsNotificationsLazyRoute: typeof SettingsNotificationsLazyRoute
  SettingsPrivacyLazyRoute: typeof SettingsPrivacyLazyRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAdvancedLazyRoute: SettingsAdvancedLazyRoute,
  SettingsExclusionsLazyRoute: SettingsExclusionsLazyRoute,
  SettingsGeneralLazyRoute: SettingsGeneralLazyRoute,
  SettingsNotificationsLazyRoute: SettingsNotificationsLazyRoute,
  SettingsPrivacyLazyRoute: SettingsPrivacyLazyRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AuthorAnalyticsLazyRoute: AuthorAnalyticsLazyRoute,
  CategoryAnalyticsLazyRoute: CategoryAnalyticsLazyRoute,
  DevicesLazyRoute: DevicesLazyRoute,
  GeographicLazyRoute: GeographicLazyRoute,
  OverviewLazyRoute: OverviewLazyRoute,
  PageAnalyticsLazyRoute: PageAnalyticsLazyRoute,
  visitorInsightsLoggedInUsersRoute: visitorInsightsLoggedInUsersRoute,
  visitorInsightsTopVisitorsRoute: visitorInsightsTopVisitorsRoute,
  visitorInsightsViewsRoute: visitorInsightsViewsRoute,
  visitorInsightsVisitorsRoute: visitorInsightsVisitorsRoute,
  visitorInsightsVisitorsOverviewRoute: visitorInsightsVisitorsOverviewRoute,
  referralsReferredVisitorsLazyRoute: referralsReferredVisitorsLazyRoute,
  referralsReferrersLazyRoute: referralsReferrersLazyRoute,
  referralsSearchEnginesLazyRoute: referralsSearchEnginesLazyRoute,
  referralsSocialMediaLazyRoute: referralsSocialMediaLazyRoute,
  referralsSourceCategoriesLazyRoute: referralsSourceCategoriesLazyRoute,
  visitorInsightsOnlineVisitorsLazyRoute:
    visitorInsightsOnlineVisitorsLazyRoute,
  visitorInsightsSearchTermsLazyRoute: visitorInsightsSearchTermsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
