/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteRouteImport } from './routes/tools/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as visitorInsightsVisitorsOverviewRouteImport } from './routes/(visitor-insights)/visitors-overview'
import { Route as visitorInsightsVisitorsRouteImport } from './routes/(visitor-insights)/visitors'
import { Route as visitorInsightsViewsRouteImport } from './routes/(visitor-insights)/views'
import { Route as visitorInsightsTopVisitorsRouteImport } from './routes/(visitor-insights)/top-visitors'
import { Route as visitorInsightsLoggedInUsersRouteImport } from './routes/(visitor-insights)/logged-in-users'
import { Route as pageInsightsTopPagesRouteImport } from './routes/(page-insights)/top-pages'

const PageAnalyticsLazyRouteImport = createFileRoute('/page-analytics')()
const OverviewLazyRouteImport = createFileRoute('/overview')()
const GeographicLazyRouteImport = createFileRoute('/geographic')()
const DevicesLazyRouteImport = createFileRoute('/devices')()
const CategoryAnalyticsLazyRouteImport = createFileRoute(
  '/category-analytics',
)()
const AuthorAnalyticsLazyRouteImport = createFileRoute('/author-analytics')()
const ToolsSystemInfoLazyRouteImport = createFileRoute('/tools/system-info')()
const ToolsScheduledTasksLazyRouteImport = createFileRoute(
  '/tools/scheduled-tasks',
)()
const ToolsImportExportLazyRouteImport = createFileRoute(
  '/tools/import-export',
)()
const ToolsBackupsLazyRouteImport = createFileRoute('/tools/backups')()
const SettingsPrivacyLazyRouteImport = createFileRoute('/settings/privacy')()
const SettingsNotificationsLazyRouteImport = createFileRoute(
  '/settings/notifications',
)()
const SettingsGeneralLazyRouteImport = createFileRoute('/settings/general')()
const SettingsExclusionsLazyRouteImport = createFileRoute(
  '/settings/exclusions',
)()
const SettingsDisplayLazyRouteImport = createFileRoute('/settings/display')()
const SettingsDataManagementLazyRouteImport = createFileRoute(
  '/settings/data-management',
)()
const SettingsAdvancedLazyRouteImport = createFileRoute('/settings/advanced')()
const SettingsAccessLazyRouteImport = createFileRoute('/settings/access')()
const visitorInsightsSearchTermsLazyRouteImport = createFileRoute(
  '/(visitor-insights)/search-terms',
)()
const visitorInsightsOnlineVisitorsLazyRouteImport = createFileRoute(
  '/(visitor-insights)/online-visitors',
)()
const referralsSourceCategoriesLazyRouteImport = createFileRoute(
  '/(referrals)/source-categories',
)()
const referralsSocialMediaLazyRouteImport = createFileRoute(
  '/(referrals)/social-media',
)()
const referralsSearchEnginesLazyRouteImport = createFileRoute(
  '/(referrals)/search-engines',
)()
const referralsReferrersLazyRouteImport = createFileRoute(
  '/(referrals)/referrers',
)()
const referralsReferredVisitorsLazyRouteImport = createFileRoute(
  '/(referrals)/referred-visitors',
)()

const PageAnalyticsLazyRoute = PageAnalyticsLazyRouteImport.update({
  id: '/page-analytics',
  path: '/page-analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/page-analytics.lazy').then((d) => d.Route),
)
const OverviewLazyRoute = OverviewLazyRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/overview.lazy').then((d) => d.Route))
const GeographicLazyRoute = GeographicLazyRouteImport.update({
  id: '/geographic',
  path: '/geographic',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/geographic.lazy').then((d) => d.Route))
const DevicesLazyRoute = DevicesLazyRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/devices.lazy').then((d) => d.Route))
const CategoryAnalyticsLazyRoute = CategoryAnalyticsLazyRouteImport.update({
  id: '/category-analytics',
  path: '/category-analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/category-analytics.lazy').then((d) => d.Route),
)
const AuthorAnalyticsLazyRoute = AuthorAnalyticsLazyRouteImport.update({
  id: '/author-analytics',
  path: '/author-analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/author-analytics.lazy').then((d) => d.Route),
)
const ToolsRouteRoute = ToolsRouteRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ToolsSystemInfoLazyRoute = ToolsSystemInfoLazyRouteImport.update({
  id: '/system-info',
  path: '/system-info',
  getParentRoute: () => ToolsRouteRoute,
} as any).lazy(() =>
  import('./routes/tools/system-info.lazy').then((d) => d.Route),
)
const ToolsScheduledTasksLazyRoute = ToolsScheduledTasksLazyRouteImport.update({
  id: '/scheduled-tasks',
  path: '/scheduled-tasks',
  getParentRoute: () => ToolsRouteRoute,
} as any).lazy(() =>
  import('./routes/tools/scheduled-tasks.lazy').then((d) => d.Route),
)
const ToolsImportExportLazyRoute = ToolsImportExportLazyRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => ToolsRouteRoute,
} as any).lazy(() =>
  import('./routes/tools/import-export.lazy').then((d) => d.Route),
)
const ToolsBackupsLazyRoute = ToolsBackupsLazyRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => ToolsRouteRoute,
} as any).lazy(() => import('./routes/tools/backups.lazy').then((d) => d.Route))
const SettingsPrivacyLazyRoute = SettingsPrivacyLazyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/privacy.lazy').then((d) => d.Route),
)
const SettingsNotificationsLazyRoute =
  SettingsNotificationsLazyRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => SettingsRouteRoute,
  } as any).lazy(() =>
    import('./routes/settings/notifications.lazy').then((d) => d.Route),
  )
const SettingsGeneralLazyRoute = SettingsGeneralLazyRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/general.lazy').then((d) => d.Route),
)
const SettingsExclusionsLazyRoute = SettingsExclusionsLazyRouteImport.update({
  id: '/exclusions',
  path: '/exclusions',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/exclusions.lazy').then((d) => d.Route),
)
const SettingsDisplayLazyRoute = SettingsDisplayLazyRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/display.lazy').then((d) => d.Route),
)
const SettingsDataManagementLazyRoute =
  SettingsDataManagementLazyRouteImport.update({
    id: '/data-management',
    path: '/data-management',
    getParentRoute: () => SettingsRouteRoute,
  } as any).lazy(() =>
    import('./routes/settings/data-management.lazy').then((d) => d.Route),
  )
const SettingsAdvancedLazyRoute = SettingsAdvancedLazyRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/advanced.lazy').then((d) => d.Route),
)
const SettingsAccessLazyRoute = SettingsAccessLazyRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/access.lazy').then((d) => d.Route),
)
const visitorInsightsSearchTermsLazyRoute =
  visitorInsightsSearchTermsLazyRouteImport
    .update({
      id: '/(visitor-insights)/search-terms',
      path: '/search-terms',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(visitor-insights)/search-terms.lazy').then(
        (d) => d.Route,
      ),
    )
const visitorInsightsOnlineVisitorsLazyRoute =
  visitorInsightsOnlineVisitorsLazyRouteImport
    .update({
      id: '/(visitor-insights)/online-visitors',
      path: '/online-visitors',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(visitor-insights)/online-visitors.lazy').then(
        (d) => d.Route,
      ),
    )
const referralsSourceCategoriesLazyRoute =
  referralsSourceCategoriesLazyRouteImport
    .update({
      id: '/(referrals)/source-categories',
      path: '/source-categories',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(referrals)/source-categories.lazy').then(
        (d) => d.Route,
      ),
    )
const referralsSocialMediaLazyRoute = referralsSocialMediaLazyRouteImport
  .update({
    id: '/(referrals)/social-media',
    path: '/social-media',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(referrals)/social-media.lazy').then((d) => d.Route),
  )
const referralsSearchEnginesLazyRoute = referralsSearchEnginesLazyRouteImport
  .update({
    id: '/(referrals)/search-engines',
    path: '/search-engines',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(referrals)/search-engines.lazy').then((d) => d.Route),
  )
const referralsReferrersLazyRoute = referralsReferrersLazyRouteImport
  .update({
    id: '/(referrals)/referrers',
    path: '/referrers',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(referrals)/referrers.lazy').then((d) => d.Route),
  )
const referralsReferredVisitorsLazyRoute =
  referralsReferredVisitorsLazyRouteImport
    .update({
      id: '/(referrals)/referred-visitors',
      path: '/referred-visitors',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(referrals)/referred-visitors.lazy').then(
        (d) => d.Route,
      ),
    )
const visitorInsightsVisitorsOverviewRoute =
  visitorInsightsVisitorsOverviewRouteImport
    .update({
      id: '/(visitor-insights)/visitors-overview',
      path: '/visitors-overview',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(visitor-insights)/visitors-overview.lazy').then(
        (d) => d.Route,
      ),
    )
const visitorInsightsVisitorsRoute = visitorInsightsVisitorsRouteImport
  .update({
    id: '/(visitor-insights)/visitors',
    path: '/visitors',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(visitor-insights)/visitors.lazy').then((d) => d.Route),
  )
const visitorInsightsViewsRoute = visitorInsightsViewsRouteImport
  .update({
    id: '/(visitor-insights)/views',
    path: '/views',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(visitor-insights)/views.lazy').then((d) => d.Route),
  )
const visitorInsightsTopVisitorsRoute = visitorInsightsTopVisitorsRouteImport
  .update({
    id: '/(visitor-insights)/top-visitors',
    path: '/top-visitors',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(visitor-insights)/top-visitors.lazy').then(
      (d) => d.Route,
    ),
  )
const visitorInsightsLoggedInUsersRoute =
  visitorInsightsLoggedInUsersRouteImport
    .update({
      id: '/(visitor-insights)/logged-in-users',
      path: '/logged-in-users',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(visitor-insights)/logged-in-users.lazy').then(
        (d) => d.Route,
      ),
    )
const pageInsightsTopPagesRoute = pageInsightsTopPagesRouteImport
  .update({
    id: '/(page-insights)/top-pages',
    path: '/top-pages',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(page-insights)/top-pages.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/tools': typeof ToolsRouteRouteWithChildren
  '/author-analytics': typeof AuthorAnalyticsLazyRoute
  '/category-analytics': typeof CategoryAnalyticsLazyRoute
  '/devices': typeof DevicesLazyRoute
  '/geographic': typeof GeographicLazyRoute
  '/overview': typeof OverviewLazyRoute
  '/page-analytics': typeof PageAnalyticsLazyRoute
  '/top-pages': typeof pageInsightsTopPagesRoute
  '/logged-in-users': typeof visitorInsightsLoggedInUsersRoute
  '/top-visitors': typeof visitorInsightsTopVisitorsRoute
  '/views': typeof visitorInsightsViewsRoute
  '/visitors': typeof visitorInsightsVisitorsRoute
  '/visitors-overview': typeof visitorInsightsVisitorsOverviewRoute
  '/referred-visitors': typeof referralsReferredVisitorsLazyRoute
  '/referrers': typeof referralsReferrersLazyRoute
  '/search-engines': typeof referralsSearchEnginesLazyRoute
  '/social-media': typeof referralsSocialMediaLazyRoute
  '/source-categories': typeof referralsSourceCategoriesLazyRoute
  '/online-visitors': typeof visitorInsightsOnlineVisitorsLazyRoute
  '/search-terms': typeof visitorInsightsSearchTermsLazyRoute
  '/settings/access': typeof SettingsAccessLazyRoute
  '/settings/advanced': typeof SettingsAdvancedLazyRoute
  '/settings/data-management': typeof SettingsDataManagementLazyRoute
  '/settings/display': typeof SettingsDisplayLazyRoute
  '/settings/exclusions': typeof SettingsExclusionsLazyRoute
  '/settings/general': typeof SettingsGeneralLazyRoute
  '/settings/notifications': typeof SettingsNotificationsLazyRoute
  '/settings/privacy': typeof SettingsPrivacyLazyRoute
  '/tools/backups': typeof ToolsBackupsLazyRoute
  '/tools/import-export': typeof ToolsImportExportLazyRoute
  '/tools/scheduled-tasks': typeof ToolsScheduledTasksLazyRoute
  '/tools/system-info': typeof ToolsSystemInfoLazyRoute
  '/settings/': typeof SettingsIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/author-analytics': typeof AuthorAnalyticsLazyRoute
  '/category-analytics': typeof CategoryAnalyticsLazyRoute
  '/devices': typeof DevicesLazyRoute
  '/geographic': typeof GeographicLazyRoute
  '/overview': typeof OverviewLazyRoute
  '/page-analytics': typeof PageAnalyticsLazyRoute
  '/top-pages': typeof pageInsightsTopPagesRoute
  '/logged-in-users': typeof visitorInsightsLoggedInUsersRoute
  '/top-visitors': typeof visitorInsightsTopVisitorsRoute
  '/views': typeof visitorInsightsViewsRoute
  '/visitors': typeof visitorInsightsVisitorsRoute
  '/visitors-overview': typeof visitorInsightsVisitorsOverviewRoute
  '/referred-visitors': typeof referralsReferredVisitorsLazyRoute
  '/referrers': typeof referralsReferrersLazyRoute
  '/search-engines': typeof referralsSearchEnginesLazyRoute
  '/social-media': typeof referralsSocialMediaLazyRoute
  '/source-categories': typeof referralsSourceCategoriesLazyRoute
  '/online-visitors': typeof visitorInsightsOnlineVisitorsLazyRoute
  '/search-terms': typeof visitorInsightsSearchTermsLazyRoute
  '/settings/access': typeof SettingsAccessLazyRoute
  '/settings/advanced': typeof SettingsAdvancedLazyRoute
  '/settings/data-management': typeof SettingsDataManagementLazyRoute
  '/settings/display': typeof SettingsDisplayLazyRoute
  '/settings/exclusions': typeof SettingsExclusionsLazyRoute
  '/settings/general': typeof SettingsGeneralLazyRoute
  '/settings/notifications': typeof SettingsNotificationsLazyRoute
  '/settings/privacy': typeof SettingsPrivacyLazyRoute
  '/tools/backups': typeof ToolsBackupsLazyRoute
  '/tools/import-export': typeof ToolsImportExportLazyRoute
  '/tools/scheduled-tasks': typeof ToolsScheduledTasksLazyRoute
  '/tools/system-info': typeof ToolsSystemInfoLazyRoute
  '/settings': typeof SettingsIndexRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/tools': typeof ToolsRouteRouteWithChildren
  '/author-analytics': typeof AuthorAnalyticsLazyRoute
  '/category-analytics': typeof CategoryAnalyticsLazyRoute
  '/devices': typeof DevicesLazyRoute
  '/geographic': typeof GeographicLazyRoute
  '/overview': typeof OverviewLazyRoute
  '/page-analytics': typeof PageAnalyticsLazyRoute
  '/(page-insights)/top-pages': typeof pageInsightsTopPagesRoute
  '/(visitor-insights)/logged-in-users': typeof visitorInsightsLoggedInUsersRoute
  '/(visitor-insights)/top-visitors': typeof visitorInsightsTopVisitorsRoute
  '/(visitor-insights)/views': typeof visitorInsightsViewsRoute
  '/(visitor-insights)/visitors': typeof visitorInsightsVisitorsRoute
  '/(visitor-insights)/visitors-overview': typeof visitorInsightsVisitorsOverviewRoute
  '/(referrals)/referred-visitors': typeof referralsReferredVisitorsLazyRoute
  '/(referrals)/referrers': typeof referralsReferrersLazyRoute
  '/(referrals)/search-engines': typeof referralsSearchEnginesLazyRoute
  '/(referrals)/social-media': typeof referralsSocialMediaLazyRoute
  '/(referrals)/source-categories': typeof referralsSourceCategoriesLazyRoute
  '/(visitor-insights)/online-visitors': typeof visitorInsightsOnlineVisitorsLazyRoute
  '/(visitor-insights)/search-terms': typeof visitorInsightsSearchTermsLazyRoute
  '/settings/access': typeof SettingsAccessLazyRoute
  '/settings/advanced': typeof SettingsAdvancedLazyRoute
  '/settings/data-management': typeof SettingsDataManagementLazyRoute
  '/settings/display': typeof SettingsDisplayLazyRoute
  '/settings/exclusions': typeof SettingsExclusionsLazyRoute
  '/settings/general': typeof SettingsGeneralLazyRoute
  '/settings/notifications': typeof SettingsNotificationsLazyRoute
  '/settings/privacy': typeof SettingsPrivacyLazyRoute
  '/tools/backups': typeof ToolsBackupsLazyRoute
  '/tools/import-export': typeof ToolsImportExportLazyRoute
  '/tools/scheduled-tasks': typeof ToolsScheduledTasksLazyRoute
  '/tools/system-info': typeof ToolsSystemInfoLazyRoute
  '/settings/': typeof SettingsIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/tools'
    | '/author-analytics'
    | '/category-analytics'
    | '/devices'
    | '/geographic'
    | '/overview'
    | '/page-analytics'
    | '/top-pages'
    | '/logged-in-users'
    | '/top-visitors'
    | '/views'
    | '/visitors'
    | '/visitors-overview'
    | '/referred-visitors'
    | '/referrers'
    | '/search-engines'
    | '/social-media'
    | '/source-categories'
    | '/online-visitors'
    | '/search-terms'
    | '/settings/access'
    | '/settings/advanced'
    | '/settings/data-management'
    | '/settings/display'
    | '/settings/exclusions'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/tools/backups'
    | '/tools/import-export'
    | '/tools/scheduled-tasks'
    | '/tools/system-info'
    | '/settings/'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/author-analytics'
    | '/category-analytics'
    | '/devices'
    | '/geographic'
    | '/overview'
    | '/page-analytics'
    | '/top-pages'
    | '/logged-in-users'
    | '/top-visitors'
    | '/views'
    | '/visitors'
    | '/visitors-overview'
    | '/referred-visitors'
    | '/referrers'
    | '/search-engines'
    | '/social-media'
    | '/source-categories'
    | '/online-visitors'
    | '/search-terms'
    | '/settings/access'
    | '/settings/advanced'
    | '/settings/data-management'
    | '/settings/display'
    | '/settings/exclusions'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/tools/backups'
    | '/tools/import-export'
    | '/tools/scheduled-tasks'
    | '/tools/system-info'
    | '/settings'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/tools'
    | '/author-analytics'
    | '/category-analytics'
    | '/devices'
    | '/geographic'
    | '/overview'
    | '/page-analytics'
    | '/(page-insights)/top-pages'
    | '/(visitor-insights)/logged-in-users'
    | '/(visitor-insights)/top-visitors'
    | '/(visitor-insights)/views'
    | '/(visitor-insights)/visitors'
    | '/(visitor-insights)/visitors-overview'
    | '/(referrals)/referred-visitors'
    | '/(referrals)/referrers'
    | '/(referrals)/search-engines'
    | '/(referrals)/social-media'
    | '/(referrals)/source-categories'
    | '/(visitor-insights)/online-visitors'
    | '/(visitor-insights)/search-terms'
    | '/settings/access'
    | '/settings/advanced'
    | '/settings/data-management'
    | '/settings/display'
    | '/settings/exclusions'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/tools/backups'
    | '/tools/import-export'
    | '/tools/scheduled-tasks'
    | '/tools/system-info'
    | '/settings/'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  ToolsRouteRoute: typeof ToolsRouteRouteWithChildren
  AuthorAnalyticsLazyRoute: typeof AuthorAnalyticsLazyRoute
  CategoryAnalyticsLazyRoute: typeof CategoryAnalyticsLazyRoute
  DevicesLazyRoute: typeof DevicesLazyRoute
  GeographicLazyRoute: typeof GeographicLazyRoute
  OverviewLazyRoute: typeof OverviewLazyRoute
  PageAnalyticsLazyRoute: typeof PageAnalyticsLazyRoute
  pageInsightsTopPagesRoute: typeof pageInsightsTopPagesRoute
  visitorInsightsLoggedInUsersRoute: typeof visitorInsightsLoggedInUsersRoute
  visitorInsightsTopVisitorsRoute: typeof visitorInsightsTopVisitorsRoute
  visitorInsightsViewsRoute: typeof visitorInsightsViewsRoute
  visitorInsightsVisitorsRoute: typeof visitorInsightsVisitorsRoute
  visitorInsightsVisitorsOverviewRoute: typeof visitorInsightsVisitorsOverviewRoute
  referralsReferredVisitorsLazyRoute: typeof referralsReferredVisitorsLazyRoute
  referralsReferrersLazyRoute: typeof referralsReferrersLazyRoute
  referralsSearchEnginesLazyRoute: typeof referralsSearchEnginesLazyRoute
  referralsSocialMediaLazyRoute: typeof referralsSocialMediaLazyRoute
  referralsSourceCategoriesLazyRoute: typeof referralsSourceCategoriesLazyRoute
  visitorInsightsOnlineVisitorsLazyRoute: typeof visitorInsightsOnlineVisitorsLazyRoute
  visitorInsightsSearchTermsLazyRoute: typeof visitorInsightsSearchTermsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/page-analytics': {
      id: '/page-analytics'
      path: '/page-analytics'
      fullPath: '/page-analytics'
      preLoaderRoute: typeof PageAnalyticsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geographic': {
      id: '/geographic'
      path: '/geographic'
      fullPath: '/geographic'
      preLoaderRoute: typeof GeographicLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category-analytics': {
      id: '/category-analytics'
      path: '/category-analytics'
      fullPath: '/category-analytics'
      preLoaderRoute: typeof CategoryAnalyticsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author-analytics': {
      id: '/author-analytics'
      path: '/author-analytics'
      fullPath: '/author-analytics'
      preLoaderRoute: typeof AuthorAnalyticsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/tools/system-info': {
      id: '/tools/system-info'
      path: '/system-info'
      fullPath: '/tools/system-info'
      preLoaderRoute: typeof ToolsSystemInfoLazyRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/tools/scheduled-tasks': {
      id: '/tools/scheduled-tasks'
      path: '/scheduled-tasks'
      fullPath: '/tools/scheduled-tasks'
      preLoaderRoute: typeof ToolsScheduledTasksLazyRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/tools/import-export': {
      id: '/tools/import-export'
      path: '/import-export'
      fullPath: '/tools/import-export'
      preLoaderRoute: typeof ToolsImportExportLazyRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/tools/backups': {
      id: '/tools/backups'
      path: '/backups'
      fullPath: '/tools/backups'
      preLoaderRoute: typeof ToolsBackupsLazyRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/exclusions': {
      id: '/settings/exclusions'
      path: '/exclusions'
      fullPath: '/settings/exclusions'
      preLoaderRoute: typeof SettingsExclusionsLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/display': {
      id: '/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof SettingsDisplayLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/data-management': {
      id: '/settings/data-management'
      path: '/data-management'
      fullPath: '/settings/data-management'
      preLoaderRoute: typeof SettingsDataManagementLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/advanced': {
      id: '/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof SettingsAdvancedLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/access': {
      id: '/settings/access'
      path: '/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof SettingsAccessLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/(visitor-insights)/search-terms': {
      id: '/(visitor-insights)/search-terms'
      path: '/search-terms'
      fullPath: '/search-terms'
      preLoaderRoute: typeof visitorInsightsSearchTermsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visitor-insights)/online-visitors': {
      id: '/(visitor-insights)/online-visitors'
      path: '/online-visitors'
      fullPath: '/online-visitors'
      preLoaderRoute: typeof visitorInsightsOnlineVisitorsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(referrals)/source-categories': {
      id: '/(referrals)/source-categories'
      path: '/source-categories'
      fullPath: '/source-categories'
      preLoaderRoute: typeof referralsSourceCategoriesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(referrals)/social-media': {
      id: '/(referrals)/social-media'
      path: '/social-media'
      fullPath: '/social-media'
      preLoaderRoute: typeof referralsSocialMediaLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(referrals)/search-engines': {
      id: '/(referrals)/search-engines'
      path: '/search-engines'
      fullPath: '/search-engines'
      preLoaderRoute: typeof referralsSearchEnginesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(referrals)/referrers': {
      id: '/(referrals)/referrers'
      path: '/referrers'
      fullPath: '/referrers'
      preLoaderRoute: typeof referralsReferrersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(referrals)/referred-visitors': {
      id: '/(referrals)/referred-visitors'
      path: '/referred-visitors'
      fullPath: '/referred-visitors'
      preLoaderRoute: typeof referralsReferredVisitorsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visitor-insights)/visitors-overview': {
      id: '/(visitor-insights)/visitors-overview'
      path: '/visitors-overview'
      fullPath: '/visitors-overview'
      preLoaderRoute: typeof visitorInsightsVisitorsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visitor-insights)/visitors': {
      id: '/(visitor-insights)/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof visitorInsightsVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visitor-insights)/views': {
      id: '/(visitor-insights)/views'
      path: '/views'
      fullPath: '/views'
      preLoaderRoute: typeof visitorInsightsViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visitor-insights)/top-visitors': {
      id: '/(visitor-insights)/top-visitors'
      path: '/top-visitors'
      fullPath: '/top-visitors'
      preLoaderRoute: typeof visitorInsightsTopVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visitor-insights)/logged-in-users': {
      id: '/(visitor-insights)/logged-in-users'
      path: '/logged-in-users'
      fullPath: '/logged-in-users'
      preLoaderRoute: typeof visitorInsightsLoggedInUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(page-insights)/top-pages': {
      id: '/(page-insights)/top-pages'
      path: '/top-pages'
      fullPath: '/top-pages'
      preLoaderRoute: typeof pageInsightsTopPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsAccessLazyRoute: typeof SettingsAccessLazyRoute
  SettingsAdvancedLazyRoute: typeof SettingsAdvancedLazyRoute
  SettingsDataManagementLazyRoute: typeof SettingsDataManagementLazyRoute
  SettingsDisplayLazyRoute: typeof SettingsDisplayLazyRoute
  SettingsExclusionsLazyRoute: typeof SettingsExclusionsLazyRoute
  SettingsGeneralLazyRoute: typeof SettingsGeneralLazyRoute
  SettingsNotificationsLazyRoute: typeof SettingsNotificationsLazyRoute
  SettingsPrivacyLazyRoute: typeof SettingsPrivacyLazyRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAccessLazyRoute: SettingsAccessLazyRoute,
  SettingsAdvancedLazyRoute: SettingsAdvancedLazyRoute,
  SettingsDataManagementLazyRoute: SettingsDataManagementLazyRoute,
  SettingsDisplayLazyRoute: SettingsDisplayLazyRoute,
  SettingsExclusionsLazyRoute: SettingsExclusionsLazyRoute,
  SettingsGeneralLazyRoute: SettingsGeneralLazyRoute,
  SettingsNotificationsLazyRoute: SettingsNotificationsLazyRoute,
  SettingsPrivacyLazyRoute: SettingsPrivacyLazyRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface ToolsRouteRouteChildren {
  ToolsBackupsLazyRoute: typeof ToolsBackupsLazyRoute
  ToolsImportExportLazyRoute: typeof ToolsImportExportLazyRoute
  ToolsScheduledTasksLazyRoute: typeof ToolsScheduledTasksLazyRoute
  ToolsSystemInfoLazyRoute: typeof ToolsSystemInfoLazyRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteRouteChildren: ToolsRouteRouteChildren = {
  ToolsBackupsLazyRoute: ToolsBackupsLazyRoute,
  ToolsImportExportLazyRoute: ToolsImportExportLazyRoute,
  ToolsScheduledTasksLazyRoute: ToolsScheduledTasksLazyRoute,
  ToolsSystemInfoLazyRoute: ToolsSystemInfoLazyRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteRouteWithChildren = ToolsRouteRoute._addFileChildren(
  ToolsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  ToolsRouteRoute: ToolsRouteRouteWithChildren,
  AuthorAnalyticsLazyRoute: AuthorAnalyticsLazyRoute,
  CategoryAnalyticsLazyRoute: CategoryAnalyticsLazyRoute,
  DevicesLazyRoute: DevicesLazyRoute,
  GeographicLazyRoute: GeographicLazyRoute,
  OverviewLazyRoute: OverviewLazyRoute,
  PageAnalyticsLazyRoute: PageAnalyticsLazyRoute,
  pageInsightsTopPagesRoute: pageInsightsTopPagesRoute,
  visitorInsightsLoggedInUsersRoute: visitorInsightsLoggedInUsersRoute,
  visitorInsightsTopVisitorsRoute: visitorInsightsTopVisitorsRoute,
  visitorInsightsViewsRoute: visitorInsightsViewsRoute,
  visitorInsightsVisitorsRoute: visitorInsightsVisitorsRoute,
  visitorInsightsVisitorsOverviewRoute: visitorInsightsVisitorsOverviewRoute,
  referralsReferredVisitorsLazyRoute: referralsReferredVisitorsLazyRoute,
  referralsReferrersLazyRoute: referralsReferrersLazyRoute,
  referralsSearchEnginesLazyRoute: referralsSearchEnginesLazyRoute,
  referralsSocialMediaLazyRoute: referralsSocialMediaLazyRoute,
  referralsSourceCategoriesLazyRoute: referralsSourceCategoriesLazyRoute,
  visitorInsightsOnlineVisitorsLazyRoute:
    visitorInsightsOnlineVisitorsLazyRoute,
  visitorInsightsSearchTermsLazyRoute: visitorInsightsSearchTermsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
