/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as NetworkOverviewRouteImport } from './routes/network-overview'
import { Route as ToolsRouteRouteImport } from './routes/tools/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as visitorInsightsVisitorsOverviewRouteImport } from './routes/(visitor-insights)/visitors-overview'
import { Route as visitorInsightsVisitorsRouteImport } from './routes/(visitor-insights)/visitors'
import { Route as visitorInsightsViewsRouteImport } from './routes/(visitor-insights)/views'
import { Route as visitorInsightsTopVisitorsRouteImport } from './routes/(visitor-insights)/top-visitors'
import { Route as visitorInsightsLoggedInUsersRouteImport } from './routes/(visitor-insights)/logged-in-users'
import { Route as referralsReferralsOverviewRouteImport } from './routes/(referrals)/referrals-overview'
import { Route as pageInsightsTopPagesRouteImport } from './routes/(page-insights)/top-pages'
import { Route as pageInsightsCategoryPagesRouteImport } from './routes/(page-insights)/category-pages'
import { Route as pageInsightsAuthorPagesRouteImport } from './routes/(page-insights)/author-pages'
import { Route as pageInsights404PagesRouteImport } from './routes/(page-insights)/404-pages'
import { Route as contentAnalyticsTopCategoriesRouteImport } from './routes/(content-analytics)/top-categories'
import { Route as contentAnalyticsTopAuthorsRouteImport } from './routes/(content-analytics)/top-authors'
import { Route as contentAnalyticsIndividualContentRouteImport } from './routes/(content-analytics)/individual-content'
import { Route as contentAnalyticsIndividualCategoryRouteImport } from './routes/(content-analytics)/individual-category'
import { Route as contentAnalyticsIndividualAuthorRouteImport } from './routes/(content-analytics)/individual-author'
import { Route as contentAnalyticsContentRouteImport } from './routes/(content-analytics)/content'
import { Route as contentAnalyticsCategoriesRouteImport } from './routes/(content-analytics)/categories'
import { Route as contentAnalyticsAuthorsRouteImport } from './routes/(content-analytics)/authors'

const PageAnalyticsLazyRouteImport = createFileRoute('/page-analytics')()
const OverviewLazyRouteImport = createFileRoute('/overview')()
const GeographicLazyRouteImport = createFileRoute('/geographic')()
const DevicesLazyRouteImport = createFileRoute('/devices')()
const CategoryAnalyticsLazyRouteImport = createFileRoute(
  '/category-analytics',
)()
const AuthorAnalyticsLazyRouteImport = createFileRoute('/author-analytics')()
const ToolsSystemInfoLazyRouteImport = createFileRoute('/tools/system-info')()
const ToolsScheduledTasksLazyRouteImport = createFileRoute(
  '/tools/scheduled-tasks',
)()
const ToolsImportExportLazyRouteImport = createFileRoute(
  '/tools/import-export',
)()
const ToolsDiagnosticsLazyRouteImport = createFileRoute('/tools/diagnostics')()
const ToolsBackupsLazyRouteImport = createFileRoute('/tools/backups')()
const ToolsBackgroundJobsLazyRouteImport = createFileRoute(
  '/tools/background-jobs',
)()
const SettingsPrivacyLazyRouteImport = createFileRoute('/settings/privacy')()
const SettingsNotificationsLazyRouteImport = createFileRoute(
  '/settings/notifications',
)()
const SettingsGeneralLazyRouteImport = createFileRoute('/settings/general')()
const SettingsExclusionsLazyRouteImport = createFileRoute(
  '/settings/exclusions',
)()
const SettingsDisplayLazyRouteImport = createFileRoute('/settings/display')()
const SettingsDataManagementLazyRouteImport = createFileRoute(
  '/settings/data-management',
)()
const SettingsAdvancedLazyRouteImport = createFileRoute('/settings/advanced')()
const SettingsAccessLazyRouteImport = createFileRoute('/settings/access')()
const visitorInsightsSearchTermsLazyRouteImport = createFileRoute(
  '/(visitor-insights)/search-terms',
)()
const visitorInsightsOnlineVisitorsLazyRouteImport = createFileRoute(
  '/(visitor-insights)/online-visitors',
)()
const referralsSourceCategoriesLazyRouteImport = createFileRoute(
  '/(referrals)/source-categories',
)()
const referralsSocialMediaLazyRouteImport = createFileRoute(
  '/(referrals)/social-media',
)()
const referralsSearchEnginesLazyRouteImport = createFileRoute(
  '/(referrals)/search-engines',
)()
const referralsReferrersLazyRouteImport = createFileRoute(
  '/(referrals)/referrers',
)()
const referralsReferredVisitorsLazyRouteImport = createFileRoute(
  '/(referrals)/referred-visitors',
)()
const referralsCampaignsLazyRouteImport = createFileRoute(
  '/(referrals)/campaigns',
)()

const PageAnalyticsLazyRoute = PageAnalyticsLazyRouteImport.update({
  id: '/page-analytics',
  path: '/page-analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/page-analytics.lazy').then((d) => d.Route),
)
const OverviewLazyRoute = OverviewLazyRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/overview.lazy').then((d) => d.Route))
const GeographicLazyRoute = GeographicLazyRouteImport.update({
  id: '/geographic',
  path: '/geographic',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/geographic.lazy').then((d) => d.Route))
const DevicesLazyRoute = DevicesLazyRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/devices.lazy').then((d) => d.Route))
const CategoryAnalyticsLazyRoute = CategoryAnalyticsLazyRouteImport.update({
  id: '/category-analytics',
  path: '/category-analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/category-analytics.lazy').then((d) => d.Route),
)
const AuthorAnalyticsLazyRoute = AuthorAnalyticsLazyRouteImport.update({
  id: '/author-analytics',
  path: '/author-analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/author-analytics.lazy').then((d) => d.Route),
)
const NetworkOverviewRoute = NetworkOverviewRouteImport.update({
  id: '/network-overview',
  path: '/network-overview',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/network-overview.lazy').then((d) => d.Route),
)
const ToolsRouteRoute = ToolsRouteRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ToolsSystemInfoLazyRoute = ToolsSystemInfoLazyRouteImport.update({
  id: '/system-info',
  path: '/system-info',
  getParentRoute: () => ToolsRouteRoute,
} as any).lazy(() =>
  import('./routes/tools/system-info.lazy').then((d) => d.Route),
)
const ToolsScheduledTasksLazyRoute = ToolsScheduledTasksLazyRouteImport.update({
  id: '/scheduled-tasks',
  path: '/scheduled-tasks',
  getParentRoute: () => ToolsRouteRoute,
} as any).lazy(() =>
  import('./routes/tools/scheduled-tasks.lazy').then((d) => d.Route),
)
const ToolsImportExportLazyRoute = ToolsImportExportLazyRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => ToolsRouteRoute,
} as any).lazy(() =>
  import('./routes/tools/import-export.lazy').then((d) => d.Route),
)
const ToolsDiagnosticsLazyRoute = ToolsDiagnosticsLazyRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => ToolsRouteRoute,
} as any).lazy(() =>
  import('./routes/tools/diagnostics.lazy').then((d) => d.Route),
)
const ToolsBackupsLazyRoute = ToolsBackupsLazyRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => ToolsRouteRoute,
} as any).lazy(() => import('./routes/tools/backups.lazy').then((d) => d.Route))
const ToolsBackgroundJobsLazyRoute = ToolsBackgroundJobsLazyRouteImport.update({
  id: '/background-jobs',
  path: '/background-jobs',
  getParentRoute: () => ToolsRouteRoute,
} as any).lazy(() =>
  import('./routes/tools/background-jobs.lazy').then((d) => d.Route),
)
const SettingsPrivacyLazyRoute = SettingsPrivacyLazyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/privacy.lazy').then((d) => d.Route),
)
const SettingsNotificationsLazyRoute =
  SettingsNotificationsLazyRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => SettingsRouteRoute,
  } as any).lazy(() =>
    import('./routes/settings/notifications.lazy').then((d) => d.Route),
  )
const SettingsGeneralLazyRoute = SettingsGeneralLazyRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/general.lazy').then((d) => d.Route),
)
const SettingsExclusionsLazyRoute = SettingsExclusionsLazyRouteImport.update({
  id: '/exclusions',
  path: '/exclusions',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/exclusions.lazy').then((d) => d.Route),
)
const SettingsDisplayLazyRoute = SettingsDisplayLazyRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/display.lazy').then((d) => d.Route),
)
const SettingsDataManagementLazyRoute =
  SettingsDataManagementLazyRouteImport.update({
    id: '/data-management',
    path: '/data-management',
    getParentRoute: () => SettingsRouteRoute,
  } as any).lazy(() =>
    import('./routes/settings/data-management.lazy').then((d) => d.Route),
  )
const SettingsAdvancedLazyRoute = SettingsAdvancedLazyRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/advanced.lazy').then((d) => d.Route),
)
const SettingsAccessLazyRoute = SettingsAccessLazyRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/access.lazy').then((d) => d.Route),
)
const visitorInsightsSearchTermsLazyRoute =
  visitorInsightsSearchTermsLazyRouteImport
    .update({
      id: '/(visitor-insights)/search-terms',
      path: '/search-terms',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(visitor-insights)/search-terms.lazy').then(
        (d) => d.Route,
      ),
    )
const visitorInsightsOnlineVisitorsLazyRoute =
  visitorInsightsOnlineVisitorsLazyRouteImport
    .update({
      id: '/(visitor-insights)/online-visitors',
      path: '/online-visitors',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(visitor-insights)/online-visitors.lazy').then(
        (d) => d.Route,
      ),
    )
const referralsSourceCategoriesLazyRoute =
  referralsSourceCategoriesLazyRouteImport
    .update({
      id: '/(referrals)/source-categories',
      path: '/source-categories',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(referrals)/source-categories.lazy').then(
        (d) => d.Route,
      ),
    )
const referralsSocialMediaLazyRoute = referralsSocialMediaLazyRouteImport
  .update({
    id: '/(referrals)/social-media',
    path: '/social-media',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(referrals)/social-media.lazy').then((d) => d.Route),
  )
const referralsSearchEnginesLazyRoute = referralsSearchEnginesLazyRouteImport
  .update({
    id: '/(referrals)/search-engines',
    path: '/search-engines',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(referrals)/search-engines.lazy').then((d) => d.Route),
  )
const referralsReferrersLazyRoute = referralsReferrersLazyRouteImport
  .update({
    id: '/(referrals)/referrers',
    path: '/referrers',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(referrals)/referrers.lazy').then((d) => d.Route),
  )
const referralsReferredVisitorsLazyRoute =
  referralsReferredVisitorsLazyRouteImport
    .update({
      id: '/(referrals)/referred-visitors',
      path: '/referred-visitors',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(referrals)/referred-visitors.lazy').then(
        (d) => d.Route,
      ),
    )
const referralsCampaignsLazyRoute = referralsCampaignsLazyRouteImport
  .update({
    id: '/(referrals)/campaigns',
    path: '/campaigns',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(referrals)/campaigns.lazy').then((d) => d.Route),
  )
const visitorInsightsVisitorsOverviewRoute =
  visitorInsightsVisitorsOverviewRouteImport
    .update({
      id: '/(visitor-insights)/visitors-overview',
      path: '/visitors-overview',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(visitor-insights)/visitors-overview.lazy').then(
        (d) => d.Route,
      ),
    )
const visitorInsightsVisitorsRoute = visitorInsightsVisitorsRouteImport
  .update({
    id: '/(visitor-insights)/visitors',
    path: '/visitors',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(visitor-insights)/visitors.lazy').then((d) => d.Route),
  )
const visitorInsightsViewsRoute = visitorInsightsViewsRouteImport
  .update({
    id: '/(visitor-insights)/views',
    path: '/views',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(visitor-insights)/views.lazy').then((d) => d.Route),
  )
const visitorInsightsTopVisitorsRoute = visitorInsightsTopVisitorsRouteImport
  .update({
    id: '/(visitor-insights)/top-visitors',
    path: '/top-visitors',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(visitor-insights)/top-visitors.lazy').then(
      (d) => d.Route,
    ),
  )
const visitorInsightsLoggedInUsersRoute =
  visitorInsightsLoggedInUsersRouteImport
    .update({
      id: '/(visitor-insights)/logged-in-users',
      path: '/logged-in-users',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(visitor-insights)/logged-in-users.lazy').then(
        (d) => d.Route,
      ),
    )
const referralsReferralsOverviewRoute = referralsReferralsOverviewRouteImport
  .update({
    id: '/(referrals)/referrals-overview',
    path: '/referrals-overview',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(referrals)/referrals-overview.lazy').then((d) => d.Route),
  )
const pageInsightsTopPagesRoute = pageInsightsTopPagesRouteImport
  .update({
    id: '/(page-insights)/top-pages',
    path: '/top-pages',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(page-insights)/top-pages.lazy').then((d) => d.Route),
  )
const pageInsightsCategoryPagesRoute = pageInsightsCategoryPagesRouteImport
  .update({
    id: '/(page-insights)/category-pages',
    path: '/category-pages',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(page-insights)/category-pages.lazy').then((d) => d.Route),
  )
const pageInsightsAuthorPagesRoute = pageInsightsAuthorPagesRouteImport
  .update({
    id: '/(page-insights)/author-pages',
    path: '/author-pages',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(page-insights)/author-pages.lazy').then((d) => d.Route),
  )
const pageInsights404PagesRoute = pageInsights404PagesRouteImport
  .update({
    id: '/(page-insights)/404-pages',
    path: '/404-pages',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(page-insights)/404-pages.lazy').then((d) => d.Route),
  )
const contentAnalyticsTopCategoriesRoute =
  contentAnalyticsTopCategoriesRouteImport
    .update({
      id: '/(content-analytics)/top-categories',
      path: '/top-categories',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(content-analytics)/top-categories.lazy').then(
        (d) => d.Route,
      ),
    )
const contentAnalyticsTopAuthorsRoute = contentAnalyticsTopAuthorsRouteImport
  .update({
    id: '/(content-analytics)/top-authors',
    path: '/top-authors',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(content-analytics)/top-authors.lazy').then(
      (d) => d.Route,
    ),
  )
const contentAnalyticsIndividualContentRoute =
  contentAnalyticsIndividualContentRouteImport
    .update({
      id: '/(content-analytics)/individual-content',
      path: '/individual-content',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(content-analytics)/individual-content.lazy').then(
        (d) => d.Route,
      ),
    )
const contentAnalyticsIndividualCategoryRoute =
  contentAnalyticsIndividualCategoryRouteImport
    .update({
      id: '/(content-analytics)/individual-category',
      path: '/individual-category',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(content-analytics)/individual-category.lazy').then(
        (d) => d.Route,
      ),
    )
const contentAnalyticsIndividualAuthorRoute =
  contentAnalyticsIndividualAuthorRouteImport
    .update({
      id: '/(content-analytics)/individual-author',
      path: '/individual-author',
      getParentRoute: () => rootRouteImport,
    } as any)
    .lazy(() =>
      import('./routes/(content-analytics)/individual-author.lazy').then(
        (d) => d.Route,
      ),
    )
const contentAnalyticsContentRoute = contentAnalyticsContentRouteImport
  .update({
    id: '/(content-analytics)/content',
    path: '/content',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(content-analytics)/content.lazy').then((d) => d.Route),
  )
const contentAnalyticsCategoriesRoute = contentAnalyticsCategoriesRouteImport
  .update({
    id: '/(content-analytics)/categories',
    path: '/categories',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(content-analytics)/categories.lazy').then((d) => d.Route),
  )
const contentAnalyticsAuthorsRoute = contentAnalyticsAuthorsRouteImport
  .update({
    id: '/(content-analytics)/authors',
    path: '/authors',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(content-analytics)/authors.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/tools': typeof ToolsRouteRouteWithChildren
  '/network-overview': typeof NetworkOverviewRoute
  '/author-analytics': typeof AuthorAnalyticsLazyRoute
  '/category-analytics': typeof CategoryAnalyticsLazyRoute
  '/devices': typeof DevicesLazyRoute
  '/geographic': typeof GeographicLazyRoute
  '/overview': typeof OverviewLazyRoute
  '/page-analytics': typeof PageAnalyticsLazyRoute
  '/authors': typeof contentAnalyticsAuthorsRoute
  '/categories': typeof contentAnalyticsCategoriesRoute
  '/content': typeof contentAnalyticsContentRoute
  '/individual-author': typeof contentAnalyticsIndividualAuthorRoute
  '/individual-category': typeof contentAnalyticsIndividualCategoryRoute
  '/individual-content': typeof contentAnalyticsIndividualContentRoute
  '/top-authors': typeof contentAnalyticsTopAuthorsRoute
  '/top-categories': typeof contentAnalyticsTopCategoriesRoute
  '/404-pages': typeof pageInsights404PagesRoute
  '/author-pages': typeof pageInsightsAuthorPagesRoute
  '/category-pages': typeof pageInsightsCategoryPagesRoute
  '/top-pages': typeof pageInsightsTopPagesRoute
  '/referrals-overview': typeof referralsReferralsOverviewRoute
  '/logged-in-users': typeof visitorInsightsLoggedInUsersRoute
  '/top-visitors': typeof visitorInsightsTopVisitorsRoute
  '/views': typeof visitorInsightsViewsRoute
  '/visitors': typeof visitorInsightsVisitorsRoute
  '/visitors-overview': typeof visitorInsightsVisitorsOverviewRoute
  '/campaigns': typeof referralsCampaignsLazyRoute
  '/referred-visitors': typeof referralsReferredVisitorsLazyRoute
  '/referrers': typeof referralsReferrersLazyRoute
  '/search-engines': typeof referralsSearchEnginesLazyRoute
  '/social-media': typeof referralsSocialMediaLazyRoute
  '/source-categories': typeof referralsSourceCategoriesLazyRoute
  '/online-visitors': typeof visitorInsightsOnlineVisitorsLazyRoute
  '/search-terms': typeof visitorInsightsSearchTermsLazyRoute
  '/settings/access': typeof SettingsAccessLazyRoute
  '/settings/advanced': typeof SettingsAdvancedLazyRoute
  '/settings/data-management': typeof SettingsDataManagementLazyRoute
  '/settings/display': typeof SettingsDisplayLazyRoute
  '/settings/exclusions': typeof SettingsExclusionsLazyRoute
  '/settings/general': typeof SettingsGeneralLazyRoute
  '/settings/notifications': typeof SettingsNotificationsLazyRoute
  '/settings/privacy': typeof SettingsPrivacyLazyRoute
  '/tools/background-jobs': typeof ToolsBackgroundJobsLazyRoute
  '/tools/backups': typeof ToolsBackupsLazyRoute
  '/tools/diagnostics': typeof ToolsDiagnosticsLazyRoute
  '/tools/import-export': typeof ToolsImportExportLazyRoute
  '/tools/scheduled-tasks': typeof ToolsScheduledTasksLazyRoute
  '/tools/system-info': typeof ToolsSystemInfoLazyRoute
  '/settings/': typeof SettingsIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/network-overview': typeof NetworkOverviewRoute
  '/author-analytics': typeof AuthorAnalyticsLazyRoute
  '/category-analytics': typeof CategoryAnalyticsLazyRoute
  '/devices': typeof DevicesLazyRoute
  '/geographic': typeof GeographicLazyRoute
  '/overview': typeof OverviewLazyRoute
  '/page-analytics': typeof PageAnalyticsLazyRoute
  '/authors': typeof contentAnalyticsAuthorsRoute
  '/categories': typeof contentAnalyticsCategoriesRoute
  '/content': typeof contentAnalyticsContentRoute
  '/individual-author': typeof contentAnalyticsIndividualAuthorRoute
  '/individual-category': typeof contentAnalyticsIndividualCategoryRoute
  '/individual-content': typeof contentAnalyticsIndividualContentRoute
  '/top-authors': typeof contentAnalyticsTopAuthorsRoute
  '/top-categories': typeof contentAnalyticsTopCategoriesRoute
  '/404-pages': typeof pageInsights404PagesRoute
  '/author-pages': typeof pageInsightsAuthorPagesRoute
  '/category-pages': typeof pageInsightsCategoryPagesRoute
  '/top-pages': typeof pageInsightsTopPagesRoute
  '/referrals-overview': typeof referralsReferralsOverviewRoute
  '/logged-in-users': typeof visitorInsightsLoggedInUsersRoute
  '/top-visitors': typeof visitorInsightsTopVisitorsRoute
  '/views': typeof visitorInsightsViewsRoute
  '/visitors': typeof visitorInsightsVisitorsRoute
  '/visitors-overview': typeof visitorInsightsVisitorsOverviewRoute
  '/campaigns': typeof referralsCampaignsLazyRoute
  '/referred-visitors': typeof referralsReferredVisitorsLazyRoute
  '/referrers': typeof referralsReferrersLazyRoute
  '/search-engines': typeof referralsSearchEnginesLazyRoute
  '/social-media': typeof referralsSocialMediaLazyRoute
  '/source-categories': typeof referralsSourceCategoriesLazyRoute
  '/online-visitors': typeof visitorInsightsOnlineVisitorsLazyRoute
  '/search-terms': typeof visitorInsightsSearchTermsLazyRoute
  '/settings/access': typeof SettingsAccessLazyRoute
  '/settings/advanced': typeof SettingsAdvancedLazyRoute
  '/settings/data-management': typeof SettingsDataManagementLazyRoute
  '/settings/display': typeof SettingsDisplayLazyRoute
  '/settings/exclusions': typeof SettingsExclusionsLazyRoute
  '/settings/general': typeof SettingsGeneralLazyRoute
  '/settings/notifications': typeof SettingsNotificationsLazyRoute
  '/settings/privacy': typeof SettingsPrivacyLazyRoute
  '/tools/background-jobs': typeof ToolsBackgroundJobsLazyRoute
  '/tools/backups': typeof ToolsBackupsLazyRoute
  '/tools/diagnostics': typeof ToolsDiagnosticsLazyRoute
  '/tools/import-export': typeof ToolsImportExportLazyRoute
  '/tools/scheduled-tasks': typeof ToolsScheduledTasksLazyRoute
  '/tools/system-info': typeof ToolsSystemInfoLazyRoute
  '/settings': typeof SettingsIndexRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/tools': typeof ToolsRouteRouteWithChildren
  '/network-overview': typeof NetworkOverviewRoute
  '/author-analytics': typeof AuthorAnalyticsLazyRoute
  '/category-analytics': typeof CategoryAnalyticsLazyRoute
  '/devices': typeof DevicesLazyRoute
  '/geographic': typeof GeographicLazyRoute
  '/overview': typeof OverviewLazyRoute
  '/page-analytics': typeof PageAnalyticsLazyRoute
  '/(content-analytics)/authors': typeof contentAnalyticsAuthorsRoute
  '/(content-analytics)/categories': typeof contentAnalyticsCategoriesRoute
  '/(content-analytics)/content': typeof contentAnalyticsContentRoute
  '/(content-analytics)/individual-author': typeof contentAnalyticsIndividualAuthorRoute
  '/(content-analytics)/individual-category': typeof contentAnalyticsIndividualCategoryRoute
  '/(content-analytics)/individual-content': typeof contentAnalyticsIndividualContentRoute
  '/(content-analytics)/top-authors': typeof contentAnalyticsTopAuthorsRoute
  '/(content-analytics)/top-categories': typeof contentAnalyticsTopCategoriesRoute
  '/(page-insights)/404-pages': typeof pageInsights404PagesRoute
  '/(page-insights)/author-pages': typeof pageInsightsAuthorPagesRoute
  '/(page-insights)/category-pages': typeof pageInsightsCategoryPagesRoute
  '/(page-insights)/top-pages': typeof pageInsightsTopPagesRoute
  '/(referrals)/referrals-overview': typeof referralsReferralsOverviewRoute
  '/(visitor-insights)/logged-in-users': typeof visitorInsightsLoggedInUsersRoute
  '/(visitor-insights)/top-visitors': typeof visitorInsightsTopVisitorsRoute
  '/(visitor-insights)/views': typeof visitorInsightsViewsRoute
  '/(visitor-insights)/visitors': typeof visitorInsightsVisitorsRoute
  '/(visitor-insights)/visitors-overview': typeof visitorInsightsVisitorsOverviewRoute
  '/(referrals)/campaigns': typeof referralsCampaignsLazyRoute
  '/(referrals)/referred-visitors': typeof referralsReferredVisitorsLazyRoute
  '/(referrals)/referrers': typeof referralsReferrersLazyRoute
  '/(referrals)/search-engines': typeof referralsSearchEnginesLazyRoute
  '/(referrals)/social-media': typeof referralsSocialMediaLazyRoute
  '/(referrals)/source-categories': typeof referralsSourceCategoriesLazyRoute
  '/(visitor-insights)/online-visitors': typeof visitorInsightsOnlineVisitorsLazyRoute
  '/(visitor-insights)/search-terms': typeof visitorInsightsSearchTermsLazyRoute
  '/settings/access': typeof SettingsAccessLazyRoute
  '/settings/advanced': typeof SettingsAdvancedLazyRoute
  '/settings/data-management': typeof SettingsDataManagementLazyRoute
  '/settings/display': typeof SettingsDisplayLazyRoute
  '/settings/exclusions': typeof SettingsExclusionsLazyRoute
  '/settings/general': typeof SettingsGeneralLazyRoute
  '/settings/notifications': typeof SettingsNotificationsLazyRoute
  '/settings/privacy': typeof SettingsPrivacyLazyRoute
  '/tools/background-jobs': typeof ToolsBackgroundJobsLazyRoute
  '/tools/backups': typeof ToolsBackupsLazyRoute
  '/tools/diagnostics': typeof ToolsDiagnosticsLazyRoute
  '/tools/import-export': typeof ToolsImportExportLazyRoute
  '/tools/scheduled-tasks': typeof ToolsScheduledTasksLazyRoute
  '/tools/system-info': typeof ToolsSystemInfoLazyRoute
  '/settings/': typeof SettingsIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/tools'
    | '/network-overview'
    | '/author-analytics'
    | '/category-analytics'
    | '/devices'
    | '/geographic'
    | '/overview'
    | '/page-analytics'
    | '/authors'
    | '/categories'
    | '/content'
    | '/individual-author'
    | '/individual-category'
    | '/individual-content'
    | '/top-authors'
    | '/top-categories'
    | '/404-pages'
    | '/author-pages'
    | '/category-pages'
    | '/top-pages'
    | '/referrals-overview'
    | '/logged-in-users'
    | '/top-visitors'
    | '/views'
    | '/visitors'
    | '/visitors-overview'
    | '/campaigns'
    | '/referred-visitors'
    | '/referrers'
    | '/search-engines'
    | '/social-media'
    | '/source-categories'
    | '/online-visitors'
    | '/search-terms'
    | '/settings/access'
    | '/settings/advanced'
    | '/settings/data-management'
    | '/settings/display'
    | '/settings/exclusions'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/tools/background-jobs'
    | '/tools/backups'
    | '/tools/diagnostics'
    | '/tools/import-export'
    | '/tools/scheduled-tasks'
    | '/tools/system-info'
    | '/settings/'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/network-overview'
    | '/author-analytics'
    | '/category-analytics'
    | '/devices'
    | '/geographic'
    | '/overview'
    | '/page-analytics'
    | '/authors'
    | '/categories'
    | '/content'
    | '/individual-author'
    | '/individual-category'
    | '/individual-content'
    | '/top-authors'
    | '/top-categories'
    | '/404-pages'
    | '/author-pages'
    | '/category-pages'
    | '/top-pages'
    | '/referrals-overview'
    | '/logged-in-users'
    | '/top-visitors'
    | '/views'
    | '/visitors'
    | '/visitors-overview'
    | '/campaigns'
    | '/referred-visitors'
    | '/referrers'
    | '/search-engines'
    | '/social-media'
    | '/source-categories'
    | '/online-visitors'
    | '/search-terms'
    | '/settings/access'
    | '/settings/advanced'
    | '/settings/data-management'
    | '/settings/display'
    | '/settings/exclusions'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/tools/background-jobs'
    | '/tools/backups'
    | '/tools/diagnostics'
    | '/tools/import-export'
    | '/tools/scheduled-tasks'
    | '/tools/system-info'
    | '/settings'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/tools'
    | '/network-overview'
    | '/author-analytics'
    | '/category-analytics'
    | '/devices'
    | '/geographic'
    | '/overview'
    | '/page-analytics'
    | '/(content-analytics)/authors'
    | '/(content-analytics)/categories'
    | '/(content-analytics)/content'
    | '/(content-analytics)/individual-author'
    | '/(content-analytics)/individual-category'
    | '/(content-analytics)/individual-content'
    | '/(content-analytics)/top-authors'
    | '/(content-analytics)/top-categories'
    | '/(page-insights)/404-pages'
    | '/(page-insights)/author-pages'
    | '/(page-insights)/category-pages'
    | '/(page-insights)/top-pages'
    | '/(referrals)/referrals-overview'
    | '/(visitor-insights)/logged-in-users'
    | '/(visitor-insights)/top-visitors'
    | '/(visitor-insights)/views'
    | '/(visitor-insights)/visitors'
    | '/(visitor-insights)/visitors-overview'
    | '/(referrals)/campaigns'
    | '/(referrals)/referred-visitors'
    | '/(referrals)/referrers'
    | '/(referrals)/search-engines'
    | '/(referrals)/social-media'
    | '/(referrals)/source-categories'
    | '/(visitor-insights)/online-visitors'
    | '/(visitor-insights)/search-terms'
    | '/settings/access'
    | '/settings/advanced'
    | '/settings/data-management'
    | '/settings/display'
    | '/settings/exclusions'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/tools/background-jobs'
    | '/tools/backups'
    | '/tools/diagnostics'
    | '/tools/import-export'
    | '/tools/scheduled-tasks'
    | '/tools/system-info'
    | '/settings/'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  ToolsRouteRoute: typeof ToolsRouteRouteWithChildren
  NetworkOverviewRoute: typeof NetworkOverviewRoute
  AuthorAnalyticsLazyRoute: typeof AuthorAnalyticsLazyRoute
  CategoryAnalyticsLazyRoute: typeof CategoryAnalyticsLazyRoute
  DevicesLazyRoute: typeof DevicesLazyRoute
  GeographicLazyRoute: typeof GeographicLazyRoute
  OverviewLazyRoute: typeof OverviewLazyRoute
  PageAnalyticsLazyRoute: typeof PageAnalyticsLazyRoute
  contentAnalyticsAuthorsRoute: typeof contentAnalyticsAuthorsRoute
  contentAnalyticsCategoriesRoute: typeof contentAnalyticsCategoriesRoute
  contentAnalyticsContentRoute: typeof contentAnalyticsContentRoute
  contentAnalyticsIndividualAuthorRoute: typeof contentAnalyticsIndividualAuthorRoute
  contentAnalyticsIndividualCategoryRoute: typeof contentAnalyticsIndividualCategoryRoute
  contentAnalyticsIndividualContentRoute: typeof contentAnalyticsIndividualContentRoute
  contentAnalyticsTopAuthorsRoute: typeof contentAnalyticsTopAuthorsRoute
  contentAnalyticsTopCategoriesRoute: typeof contentAnalyticsTopCategoriesRoute
  pageInsights404PagesRoute: typeof pageInsights404PagesRoute
  pageInsightsAuthorPagesRoute: typeof pageInsightsAuthorPagesRoute
  pageInsightsCategoryPagesRoute: typeof pageInsightsCategoryPagesRoute
  pageInsightsTopPagesRoute: typeof pageInsightsTopPagesRoute
  referralsReferralsOverviewRoute: typeof referralsReferralsOverviewRoute
  visitorInsightsLoggedInUsersRoute: typeof visitorInsightsLoggedInUsersRoute
  visitorInsightsTopVisitorsRoute: typeof visitorInsightsTopVisitorsRoute
  visitorInsightsViewsRoute: typeof visitorInsightsViewsRoute
  visitorInsightsVisitorsRoute: typeof visitorInsightsVisitorsRoute
  visitorInsightsVisitorsOverviewRoute: typeof visitorInsightsVisitorsOverviewRoute
  referralsCampaignsLazyRoute: typeof referralsCampaignsLazyRoute
  referralsReferredVisitorsLazyRoute: typeof referralsReferredVisitorsLazyRoute
  referralsReferrersLazyRoute: typeof referralsReferrersLazyRoute
  referralsSearchEnginesLazyRoute: typeof referralsSearchEnginesLazyRoute
  referralsSocialMediaLazyRoute: typeof referralsSocialMediaLazyRoute
  referralsSourceCategoriesLazyRoute: typeof referralsSourceCategoriesLazyRoute
  visitorInsightsOnlineVisitorsLazyRoute: typeof visitorInsightsOnlineVisitorsLazyRoute
  visitorInsightsSearchTermsLazyRoute: typeof visitorInsightsSearchTermsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/page-analytics': {
      id: '/page-analytics'
      path: '/page-analytics'
      fullPath: '/page-analytics'
      preLoaderRoute: typeof PageAnalyticsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geographic': {
      id: '/geographic'
      path: '/geographic'
      fullPath: '/geographic'
      preLoaderRoute: typeof GeographicLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category-analytics': {
      id: '/category-analytics'
      path: '/category-analytics'
      fullPath: '/category-analytics'
      preLoaderRoute: typeof CategoryAnalyticsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author-analytics': {
      id: '/author-analytics'
      path: '/author-analytics'
      fullPath: '/author-analytics'
      preLoaderRoute: typeof AuthorAnalyticsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-overview': {
      id: '/network-overview'
      path: '/network-overview'
      fullPath: '/network-overview'
      preLoaderRoute: typeof NetworkOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/tools/system-info': {
      id: '/tools/system-info'
      path: '/system-info'
      fullPath: '/tools/system-info'
      preLoaderRoute: typeof ToolsSystemInfoLazyRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/tools/scheduled-tasks': {
      id: '/tools/scheduled-tasks'
      path: '/scheduled-tasks'
      fullPath: '/tools/scheduled-tasks'
      preLoaderRoute: typeof ToolsScheduledTasksLazyRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/tools/import-export': {
      id: '/tools/import-export'
      path: '/import-export'
      fullPath: '/tools/import-export'
      preLoaderRoute: typeof ToolsImportExportLazyRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/tools/diagnostics': {
      id: '/tools/diagnostics'
      path: '/diagnostics'
      fullPath: '/tools/diagnostics'
      preLoaderRoute: typeof ToolsDiagnosticsLazyRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/tools/backups': {
      id: '/tools/backups'
      path: '/backups'
      fullPath: '/tools/backups'
      preLoaderRoute: typeof ToolsBackupsLazyRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/tools/background-jobs': {
      id: '/tools/background-jobs'
      path: '/background-jobs'
      fullPath: '/tools/background-jobs'
      preLoaderRoute: typeof ToolsBackgroundJobsLazyRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/exclusions': {
      id: '/settings/exclusions'
      path: '/exclusions'
      fullPath: '/settings/exclusions'
      preLoaderRoute: typeof SettingsExclusionsLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/display': {
      id: '/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof SettingsDisplayLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/data-management': {
      id: '/settings/data-management'
      path: '/data-management'
      fullPath: '/settings/data-management'
      preLoaderRoute: typeof SettingsDataManagementLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/advanced': {
      id: '/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof SettingsAdvancedLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/access': {
      id: '/settings/access'
      path: '/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof SettingsAccessLazyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/(visitor-insights)/search-terms': {
      id: '/(visitor-insights)/search-terms'
      path: '/search-terms'
      fullPath: '/search-terms'
      preLoaderRoute: typeof visitorInsightsSearchTermsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visitor-insights)/online-visitors': {
      id: '/(visitor-insights)/online-visitors'
      path: '/online-visitors'
      fullPath: '/online-visitors'
      preLoaderRoute: typeof visitorInsightsOnlineVisitorsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(referrals)/source-categories': {
      id: '/(referrals)/source-categories'
      path: '/source-categories'
      fullPath: '/source-categories'
      preLoaderRoute: typeof referralsSourceCategoriesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(referrals)/social-media': {
      id: '/(referrals)/social-media'
      path: '/social-media'
      fullPath: '/social-media'
      preLoaderRoute: typeof referralsSocialMediaLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(referrals)/search-engines': {
      id: '/(referrals)/search-engines'
      path: '/search-engines'
      fullPath: '/search-engines'
      preLoaderRoute: typeof referralsSearchEnginesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(referrals)/referrers': {
      id: '/(referrals)/referrers'
      path: '/referrers'
      fullPath: '/referrers'
      preLoaderRoute: typeof referralsReferrersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(referrals)/referred-visitors': {
      id: '/(referrals)/referred-visitors'
      path: '/referred-visitors'
      fullPath: '/referred-visitors'
      preLoaderRoute: typeof referralsReferredVisitorsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(referrals)/campaigns': {
      id: '/(referrals)/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof referralsCampaignsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visitor-insights)/visitors-overview': {
      id: '/(visitor-insights)/visitors-overview'
      path: '/visitors-overview'
      fullPath: '/visitors-overview'
      preLoaderRoute: typeof visitorInsightsVisitorsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visitor-insights)/visitors': {
      id: '/(visitor-insights)/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof visitorInsightsVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visitor-insights)/views': {
      id: '/(visitor-insights)/views'
      path: '/views'
      fullPath: '/views'
      preLoaderRoute: typeof visitorInsightsViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visitor-insights)/top-visitors': {
      id: '/(visitor-insights)/top-visitors'
      path: '/top-visitors'
      fullPath: '/top-visitors'
      preLoaderRoute: typeof visitorInsightsTopVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(visitor-insights)/logged-in-users': {
      id: '/(visitor-insights)/logged-in-users'
      path: '/logged-in-users'
      fullPath: '/logged-in-users'
      preLoaderRoute: typeof visitorInsightsLoggedInUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(referrals)/referrals-overview': {
      id: '/(referrals)/referrals-overview'
      path: '/referrals-overview'
      fullPath: '/referrals-overview'
      preLoaderRoute: typeof referralsReferralsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(page-insights)/top-pages': {
      id: '/(page-insights)/top-pages'
      path: '/top-pages'
      fullPath: '/top-pages'
      preLoaderRoute: typeof pageInsightsTopPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(page-insights)/category-pages': {
      id: '/(page-insights)/category-pages'
      path: '/category-pages'
      fullPath: '/category-pages'
      preLoaderRoute: typeof pageInsightsCategoryPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(page-insights)/author-pages': {
      id: '/(page-insights)/author-pages'
      path: '/author-pages'
      fullPath: '/author-pages'
      preLoaderRoute: typeof pageInsightsAuthorPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(page-insights)/404-pages': {
      id: '/(page-insights)/404-pages'
      path: '/404-pages'
      fullPath: '/404-pages'
      preLoaderRoute: typeof pageInsights404PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(content-analytics)/top-categories': {
      id: '/(content-analytics)/top-categories'
      path: '/top-categories'
      fullPath: '/top-categories'
      preLoaderRoute: typeof contentAnalyticsTopCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(content-analytics)/top-authors': {
      id: '/(content-analytics)/top-authors'
      path: '/top-authors'
      fullPath: '/top-authors'
      preLoaderRoute: typeof contentAnalyticsTopAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(content-analytics)/individual-content': {
      id: '/(content-analytics)/individual-content'
      path: '/individual-content'
      fullPath: '/individual-content'
      preLoaderRoute: typeof contentAnalyticsIndividualContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(content-analytics)/individual-category': {
      id: '/(content-analytics)/individual-category'
      path: '/individual-category'
      fullPath: '/individual-category'
      preLoaderRoute: typeof contentAnalyticsIndividualCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(content-analytics)/individual-author': {
      id: '/(content-analytics)/individual-author'
      path: '/individual-author'
      fullPath: '/individual-author'
      preLoaderRoute: typeof contentAnalyticsIndividualAuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(content-analytics)/content': {
      id: '/(content-analytics)/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof contentAnalyticsContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(content-analytics)/categories': {
      id: '/(content-analytics)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof contentAnalyticsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(content-analytics)/authors': {
      id: '/(content-analytics)/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof contentAnalyticsAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsAccessLazyRoute: typeof SettingsAccessLazyRoute
  SettingsAdvancedLazyRoute: typeof SettingsAdvancedLazyRoute
  SettingsDataManagementLazyRoute: typeof SettingsDataManagementLazyRoute
  SettingsDisplayLazyRoute: typeof SettingsDisplayLazyRoute
  SettingsExclusionsLazyRoute: typeof SettingsExclusionsLazyRoute
  SettingsGeneralLazyRoute: typeof SettingsGeneralLazyRoute
  SettingsNotificationsLazyRoute: typeof SettingsNotificationsLazyRoute
  SettingsPrivacyLazyRoute: typeof SettingsPrivacyLazyRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAccessLazyRoute: SettingsAccessLazyRoute,
  SettingsAdvancedLazyRoute: SettingsAdvancedLazyRoute,
  SettingsDataManagementLazyRoute: SettingsDataManagementLazyRoute,
  SettingsDisplayLazyRoute: SettingsDisplayLazyRoute,
  SettingsExclusionsLazyRoute: SettingsExclusionsLazyRoute,
  SettingsGeneralLazyRoute: SettingsGeneralLazyRoute,
  SettingsNotificationsLazyRoute: SettingsNotificationsLazyRoute,
  SettingsPrivacyLazyRoute: SettingsPrivacyLazyRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface ToolsRouteRouteChildren {
  ToolsBackgroundJobsLazyRoute: typeof ToolsBackgroundJobsLazyRoute
  ToolsBackupsLazyRoute: typeof ToolsBackupsLazyRoute
  ToolsDiagnosticsLazyRoute: typeof ToolsDiagnosticsLazyRoute
  ToolsImportExportLazyRoute: typeof ToolsImportExportLazyRoute
  ToolsScheduledTasksLazyRoute: typeof ToolsScheduledTasksLazyRoute
  ToolsSystemInfoLazyRoute: typeof ToolsSystemInfoLazyRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteRouteChildren: ToolsRouteRouteChildren = {
  ToolsBackgroundJobsLazyRoute: ToolsBackgroundJobsLazyRoute,
  ToolsBackupsLazyRoute: ToolsBackupsLazyRoute,
  ToolsDiagnosticsLazyRoute: ToolsDiagnosticsLazyRoute,
  ToolsImportExportLazyRoute: ToolsImportExportLazyRoute,
  ToolsScheduledTasksLazyRoute: ToolsScheduledTasksLazyRoute,
  ToolsSystemInfoLazyRoute: ToolsSystemInfoLazyRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteRouteWithChildren = ToolsRouteRoute._addFileChildren(
  ToolsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  ToolsRouteRoute: ToolsRouteRouteWithChildren,
  NetworkOverviewRoute: NetworkOverviewRoute,
  AuthorAnalyticsLazyRoute: AuthorAnalyticsLazyRoute,
  CategoryAnalyticsLazyRoute: CategoryAnalyticsLazyRoute,
  DevicesLazyRoute: DevicesLazyRoute,
  GeographicLazyRoute: GeographicLazyRoute,
  OverviewLazyRoute: OverviewLazyRoute,
  PageAnalyticsLazyRoute: PageAnalyticsLazyRoute,
  contentAnalyticsAuthorsRoute: contentAnalyticsAuthorsRoute,
  contentAnalyticsCategoriesRoute: contentAnalyticsCategoriesRoute,
  contentAnalyticsContentRoute: contentAnalyticsContentRoute,
  contentAnalyticsIndividualAuthorRoute: contentAnalyticsIndividualAuthorRoute,
  contentAnalyticsIndividualCategoryRoute:
    contentAnalyticsIndividualCategoryRoute,
  contentAnalyticsIndividualContentRoute:
    contentAnalyticsIndividualContentRoute,
  contentAnalyticsTopAuthorsRoute: contentAnalyticsTopAuthorsRoute,
  contentAnalyticsTopCategoriesRoute: contentAnalyticsTopCategoriesRoute,
  pageInsights404PagesRoute: pageInsights404PagesRoute,
  pageInsightsAuthorPagesRoute: pageInsightsAuthorPagesRoute,
  pageInsightsCategoryPagesRoute: pageInsightsCategoryPagesRoute,
  pageInsightsTopPagesRoute: pageInsightsTopPagesRoute,
  referralsReferralsOverviewRoute: referralsReferralsOverviewRoute,
  visitorInsightsLoggedInUsersRoute: visitorInsightsLoggedInUsersRoute,
  visitorInsightsTopVisitorsRoute: visitorInsightsTopVisitorsRoute,
  visitorInsightsViewsRoute: visitorInsightsViewsRoute,
  visitorInsightsVisitorsRoute: visitorInsightsVisitorsRoute,
  visitorInsightsVisitorsOverviewRoute: visitorInsightsVisitorsOverviewRoute,
  referralsCampaignsLazyRoute: referralsCampaignsLazyRoute,
  referralsReferredVisitorsLazyRoute: referralsReferredVisitorsLazyRoute,
  referralsReferrersLazyRoute: referralsReferrersLazyRoute,
  referralsSearchEnginesLazyRoute: referralsSearchEnginesLazyRoute,
  referralsSocialMediaLazyRoute: referralsSocialMediaLazyRoute,
  referralsSourceCategoriesLazyRoute: referralsSourceCategoriesLazyRoute,
  visitorInsightsOnlineVisitorsLazyRoute:
    visitorInsightsOnlineVisitorsLazyRoute,
  visitorInsightsSearchTermsLazyRoute: visitorInsightsSearchTermsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
