<?php

use WP_Statistics\Components\View;
use WP_STATISTICS\Menus;

?>
<div class="metabox-holder wps-referral-overview">
    <div class="postbox-container" id="wps-postbox-container-1">

        <?php View::load("components/objects/glance-card", ['metrics' => [
            ['label' => esc_html__('Top Country', 'wp-statistics'), 'tooltip' => esc_html__('tooltip', 'wp-statistics'), 'value' => 'United States'],
            ['label' => esc_html__('Top Region', 'wp-statistics'), 'tooltip' => esc_html__('tooltip', 'wp-statistics'), 'value' => 'Harjumaa'],
            ['label' => esc_html__('Top City', 'wp-statistics'), 'tooltip' => esc_html__('tooltip', 'wp-statistics'), 'value' => 'Amsterdam'],
        ]]);

        View::load("components/tables/geographic-top-visitors", [
            'title'        => esc_html__('Regions of Estonia', 'wp-statistics'),
            'top_title'    => esc_html__('Regions', 'wp-statistics'),
            'footer_title' => esc_html__('View Regions of Estonia', 'wp-statistics'),
            'footer_link'  => esc_url(Menus::admin_url('geographic', ['tab' => 'estonia'])),
        ]);


        View::load("components/tables/geographic-top-visitors", [
            'title'        => esc_html__('Top US States', 'wp-statistics'),
            'top_title'    => esc_html__('States', 'wp-statistics'),
            'footer_title' => esc_html__('View US States', 'wp-statistics'),
            'footer_link'  => esc_url(Menus::admin_url('geographic', ['tab' => 'us'])),
        ]);


        View::load("components/charts/horizontal-bar", [
            'title'        => esc_html__('Top European Countries', 'wp-statistics'),
            'footer_title' => esc_html__('View European Countries', 'wp-statistics'),
            'footer_link'  => esc_url(Menus::admin_url('geographic', ['tab' => 'europe'])),
            'unique_id'    => 'geographic--top-countries'
        ]);

        View::load("components/charts/horizontal-bar", [
            'title'     => esc_html__('Visitors by Continent', 'wp-statistics'),
            'unique_id' => 'geographic-visitors-continent'
        ]);

        ?>
    </div>
    <div class="postbox-container" id="wps-postbox-container-2">
        <div class="wps-card">
            <div class="wps-card__title">
                <h2><?php esc_html_e('Global Visitor Map', 'wp-statistics') ?></h2>
            </div>
            <div class="inside wps-geo-map">
                <?php
                $distribution = [
                    "data" => [
                        "data"     => [
                            "6",
                            "144",
                            "9",
                            "36",
                            "24",
                            "5",
                            "224",
                            "1",
                            "838",
                            "505",
                            "5",
                            "2",
                            "15",
                            "51",
                            "4",
                            "251",
                            "394",
                            "19",
                            "172",
                            "7",
                            "26",
                            "2",
                            "17",
                            "1",
                            "579",
                            "2",
                            "44",
                            "4",
                            "893",
                            "13",
                            "3",
                            "1085",
                            "14",
                            "176",
                            "15",
                            "727",
                            "232",
                            "33",
                            "23",
                            "4",
                            "1",
                            "41",
                            "466",
                            "6478",
                            "476",
                            "59",
                            "76",
                            "49",
                            "144",
                            "263",
                            "1592",
                            "255",
                            "556",
                            "1",
                            "4",
                            "2731",
                            "1",
                            "1695",
                            "4",
                            "22",
                            "5",
                            "33",
                            "2",
                            "1",
                            "4",
                            "8",
                            "3",
                            "340",
                            "33",
                            "1",
                            "2",
                            "357",
                            "13",
                            "155",
                            "8",
                            "385",
                            "616",
                            "428",
                            "140",
                            "1070",
                            "51",
                            "3250",
                            "15",
                            "1474",
                            "2",
                            "10",
                            "44",
                            "1688",
                            "75",
                            "7",
                            "33",
                            "1",
                            "467",
                            "13",
                            "15",
                            "7",
                            "17",
                            "2",
                            "2",
                            "36",
                            "5",
                            "113",
                            "45",
                            "83",
                            "6",
                            "210",
                            "2",
                            "41",
                            "6",
                            "7",
                            "36",
                            "10",
                            "16",
                            "6",
                            "3",
                            "2",
                            "18",
                            "10",
                            "2",
                            "2",
                            "338",
                            "212",
                            "9",
                            "8",
                            "3",
                            "1",
                            "224",
                            "10",
                            "2546",
                            "219",
                            "68",
                            "110",
                            "18",
                            "31",
                            "93",
                            "6",
                            "3",
                            "181",
                            "329",
                            "1550",
                            "17",
                            "12",
                            "258",
                            "23",
                            "8",
                            "16",
                            "357",
                            "113",
                            "291",
                            "17",
                            "104",
                            "3",
                            "6",
                            "7",
                            "724",
                            "323",
                            "87",
                            "189",
                            "3",
                            "10",
                            "10",
                            "6",
                            "13",
                            "10",
                            "4",
                            "1",
                            "17",
                            "342",
                            "2",
                            "67",
                            "1",
                            "478",
                            "7",
                            "274",
                            "15",
                            "236",
                            "25",
                            "5675",
                            "36",
                            "23",
                            "1",
                            "55",
                            "1",
                            "469",
                            "3",
                            "10",
                            "17",
                            "235",
                            "8",
                            "10"
                        ],
                        "raw_data" => [
                            "6",
                            "144",
                            "9",
                            "36",
                            "24",
                            "5",
                            "224",
                            "1",
                            "838",
                            "505",
                            "5",
                            "2",
                            "15",
                            "51",
                            "4",
                            "251",
                            "394",
                            "19",
                            "172",
                            "7",
                            "26",
                            "2",
                            "17",
                            "1",
                            "579",
                            "2",
                            "44",
                            "4",
                            "893",
                            "13",
                            "3",
                            "1085",
                            "14",
                            "176",
                            "15",
                            "727",
                            "232",
                            "33",
                            "23",
                            "4",
                            "1",
                            "41",
                            "466",
                            "6478",
                            "476",
                            "59",
                            "76",
                            "49",
                            "144",
                            "263",
                            "1592",
                            "255",
                            "556",
                            "1",
                            "4",
                            "2731",
                            "1",
                            "1695",
                            "4",
                            "22",
                            "5",
                            "33",
                            "2",
                            "1",
                            "4",
                            "8",
                            "3",
                            "340",
                            "33",
                            "1",
                            "2",
                            "357",
                            "13",
                            "155",
                            "8",
                            "385",
                            "616",
                            "428",
                            "140",
                            "1070",
                            "51",
                            "3250",
                            "15",
                            "1474",
                            "2",
                            "10",
                            "44",
                            "1688",
                            "75",
                            "7",
                            "33",
                            "1",
                            "467",
                            "13",
                            "15",
                            "7",
                            "17",
                            "2",
                            "2",
                            "36",
                            "5",
                            "113",
                            "45",
                            "83",
                            "6",
                            "210",
                            "2",
                            "41",
                            "6",
                            "7",
                            "36",
                            "10",
                            "16",
                            "6",
                            "3",
                            "2",
                            "18",
                            "10",
                            "2",
                            "2",
                            "338",
                            "212",
                            "9",
                            "8",
                            "3",
                            "1",
                            "224",
                            "10",
                            "2546",
                            "219",
                            "68",
                            "110",
                            "18",
                            "31",
                            "93",
                            "6",
                            "3",
                            "181",
                            "329",
                            "1550",
                            "17",
                            "12",
                            "258",
                            "23",
                            "8",
                            "16",
                            "357",
                            "113",
                            "291",
                            "17",
                            "104",
                            "3",
                            "6",
                            "7",
                            "724",
                            "323",
                            "87",
                            "189",
                            "3",
                            "10",
                            "10",
                            "6",
                            "13",
                            "10",
                            "4",
                            "1",
                            "17",
                            "342",
                            "2",
                            "67",
                            "1",
                            "478",
                            "7",
                            "274",
                            "15",
                            "236",
                            "25",
                            "5675",
                            "36",
                            "23",
                            "1",
                            "55",
                            "1",
                            "469",
                            "3",
                            "10",
                            "17",
                            "235",
                            "8",
                            "10"
                        ]
                    ]
                ];

                View::load("metabox/global-visitor-distribution", $distribution);
                ?>
            </div>
        </div>

        <?php
        $topCountries = [
            'data' => ''
        ];
        View::load("components/tables/geographic-top-countries", $topCountries);


        $topCities = [
            'data' => ''
        ];
        View::load("components/tables/geographic-top-cities", $topCities);

        ?>
    </div>
</div>