blank_issues_enabled: true
contact_links:
  - name: 💡 Feature Request
    url: https://feedback.veronalabs.com/boards/wp-statistics
    about: Have some great ideas to improve our site or this codebase? Open a new feature request in our team's app of choice.
