<table role="presentation" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" cellspacing="0" cellpadding="0" border="0">
    <tbody>
    <tr>
        <td class="content-block" style="color: #999999; font-size: 12px; padding-bottom: 10px; padding-top: 10px; text-align: center; vertical-align: top;">
            <span class="apple-link" style="color: #999999; font-size: 12px; text-align: center;">' . __('Generated by:', 'wp-statistics') . ' <a href="https://wp-statistics.com" target="_blank" style="color: #999999; font-size: 12px; text-align: center; text-decoration: underline;">WP Statistics</a></span>
        </td>
    </tr>
    </tbody>
</table>